table dim_return_reason
	lineageTag: 113c9baf-a27b-426d-91d1-cce65b1289b2

	column ReturnReasonID
		dataType: string
		lineageTag: 8389a82d-0a76-4017-a5d8-b407094f4529
		summarizeBy: none
		sourceColumn: ReturnReasonID

		annotation SummarizationSetBy = Automatic

	column ReturnReason
		dataType: string
		lineageTag: 791e41b4-d9cc-4cde-9945-e3d2edf4204a
		summarizeBy: none
		sourceColumn: ReturnReason

		annotation SummarizationSetBy = Automatic

	partition dim_return_reason = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\CAM Tech\Downloads\BI Project\DIM\dim_return_reason.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReturnReasonID", type text}, {"ReturnReason", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

