table fact_financial_insights
	lineageTag: 1e565772-7bd4-4b5b-88d1-c7934a1f270d

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2439c1fa-1cb6-4735-b919-362152b33ae3
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Gross Sales'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 01b794ed-ff10-480a-801d-9b85f95a22c0
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column COGS
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 31036082-ebc9-4235-b536-eedac154ab53
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Gross Profit'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 56b4c17c-fd3e-4fdc-b71c-1f82d3b3d3f4
		summarizeBy: sum
		sourceColumn: Gross Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition fact_financial_insights = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\CAM Tech\Downloads\BI Project\Sales\DIM\fact_financial_insights.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Gross Sales", Currency.Type}, {"COGS", Currency.Type}, {"Gross Profit", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

