{
  "name": "Performance Dashboard",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_channel",
        "lineageTag": "664c86ce-30ca-4ae1-b57c-c81441dabaf9",
        "columns": [
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "65da6c0f-9587-4eed-ad60-2986b028f468",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChannelName",
            "dataType": "string",
            "sourceColumn": "ChannelName",
            "lineageTag": "c33b9523-45eb-43a6-b3ab-f2f9ea2b3f77",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "ChannelName (2)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dim_channel'[ChannelName],\"Marketplace\",\"B2B\",\"Wholesale (B2B)\",\"B2B\",'dim_channel'[ChannelName])",
            "lineageTag": "33cc725b-a188-4ea6-b4cc-2bceef345b36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "ChannelName (3)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dim_channel'[ChannelName],\"Marketplace\",\"B2B\",\"Wholesale (B2B)\",\"B2B\", \"Retail\",\"B2C\",\"Online\",\"B2C\",'dim_channel'[ChannelName])",
            "lineageTag": "e21c45bf-ca9c-4129-a551-2038da219b04",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "ChannelName (4)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dim_channel'[ChannelName],\"Wholesale (B2B)\",\"Wholesale\",'dim_channel'[ChannelName])",
            "lineageTag": "5f87fe34-7627-49ed-bd76-601e9025fa34",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_channel",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\DIM\\dim_channel.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ChannelID\", type text}, {\"ChannelName\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_customer",
        "lineageTag": "73d7a258-db38-4dad-8eb9-ddd60bfb66df",
        "columns": [
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "3a398a92-4659-4856-b5ff-c65694a4390f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FullName",
            "dataType": "string",
            "sourceColumn": "FullName",
            "lineageTag": "9731cb82-0b94-4198-b407-a537117b198b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerType",
            "dataType": "string",
            "sourceColumn": "CustomerType",
            "lineageTag": "8188d4d4-bd09-46a3-9d30-5e93ca17a573",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email",
            "lineageTag": "ab7b76e1-2533-4384-9310-279fce8d7a4d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone",
            "lineageTag": "5ce38b19-5d03-4d79-89f3-38392d24e257",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address",
            "lineageTag": "004775a5-2cb0-4477-baf6-7ce82184d5db",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "8f896bf6-0d30-4283-bd77-8d79b71571ea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "04ecf00c-cd37-4d9b-a2a4-28467c9ef74a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "6942604e-f968-4a84-a93c-5d1750679e70",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "6767082a-0cd1-4a5b-a409-a1f606b2a88b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PostalCode",
            "dataType": "int64",
            "sourceColumn": "PostalCode",
            "formatString": "0",
            "lineageTag": "01f2fdbf-c964-4c45-a4a2-51b0a9ff56b6",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SignupDate",
            "dataType": "dateTime",
            "sourceColumn": "SignupDate",
            "formatString": "Long Date",
            "lineageTag": "86169a63-1a27-4b7a-843b-c53d8d45a18c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "LoyaltyStatus",
            "dataType": "string",
            "sourceColumn": "LoyaltyStatus",
            "lineageTag": "6c9f6d70-439b-4966-a632-00aff7c9c376",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Customer_Priority",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "VAR MaxOrder =",
              "    CALCULATE(",
              "        MAX('fact_orders'[OrderAmount]),",
              "        FILTER('fact_orders', 'fact_orders'[CustomerID] = 'dim_customer'[CustomerID])",
              "    )",
              "RETURN",
              "SWITCH(",
              "    TRUE(),",
              "    MaxOrder < 500, \"Low\",",
              "    MaxOrder >= 500 && MaxOrder < 2500, \"Medium\",",
              "    MaxOrder >= 2500 && MaxOrder < 7000, \"High\",",
              "    MaxOrder >= 7000, \"Very High\",",
              "    \"Other\"",
              ")",
              ""
            ],
            "lineageTag": "c4099980-4bc2-401b-bfa8-c953827e6000",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "LoyaltyStatus (2)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dim_customer'[LoyaltyStatus],\"New\",\"Inactive\",'dim_customer'[LoyaltyStatus])",
            "lineageTag": "65aec20f-cbf0-40e6-a6bb-e303440915b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Country (2)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dim_customer'[Country],\"Nigeria\",\"Japan\", \"United States\",\"USA\",'dim_customer'[Country])",
            "lineageTag": "b533544d-6205-437f-9c7d-fbc4481b2511",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\DIM\\dim_customer.csv\"),[Delimiter=\",\", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerID\", type text}, {\"FullName\", type text}, {\"CustomerType\", type text}, {\"Email\", type text}, {\"Phone\", type text}, {\"Address\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Country\", type text}, {\"Region\", type text}, {\"PostalCode\", Int64.Type}, {\"SignupDate\", type date}, {\"LoyaltyStatus\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_product",
        "lineageTag": "ed550f9c-8249-4709-9b43-c56e74ee86f5",
        "columns": [
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "lineageTag": "a0a54dfc-c659-4bdf-9eba-be03166dcaab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SKU",
            "dataType": "string",
            "sourceColumn": "SKU",
            "lineageTag": "a2a6161f-2072-4e42-b181-a8645a67c7ea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName",
            "lineageTag": "3c3aad17-be61-4626-905a-6ab4abe101ab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "0292bb53-2666-4420-b91f-62ae7ea17e1e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SubCategory",
            "dataType": "string",
            "sourceColumn": "SubCategory",
            "lineageTag": "6f3e1600-d903-436e-8601-de70ff4f241e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "lineageTag": "8944a76e-d4c6-4c0a-b39b-669bd678ae0f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitCost",
            "dataType": "double",
            "sourceColumn": "UnitCost",
            "lineageTag": "0cd00bb2-5234-4e67-8054-a633838e76bc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice",
            "lineageTag": "d2d7842f-651b-4a44-beb7-872969e576d4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ProfitMargin",
            "dataType": "double",
            "sourceColumn": "ProfitMargin",
            "lineageTag": "17280f58-423d-40ca-8530-72a44fd08240",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "LaunchDate",
            "dataType": "dateTime",
            "sourceColumn": "LaunchDate",
            "formatString": "Long Date",
            "lineageTag": "9e63e69e-2f0d-41b9-8de8-cd3b3a3094e9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Discontinued",
            "dataType": "boolean",
            "sourceColumn": "Discontinued",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f31bbe72-aedc-4837-a9bb-a4ac8017508a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Column",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "4b5a7be0-5c21-475a-aa8c-323f606b1e7d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\Sales\\DIM\\dim_product.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductID\", type text}, {\"SKU\", type text}, {\"ProductName\", type text}, {\"Category\", type text}, {\"SubCategory\", type text}, {\"Brand\", type text}, {\"UnitCost\", type number}, {\"UnitPrice\", type number}, {\"ProfitMargin\", type number}, {\"LaunchDate\", type date}, {\"Discontinued\", type logical}}),",
                "    #\"Extracted Text Before Delimiter\" = Table.TransformColumns(#\"Changed Type\", {{\"ProductName\", each Text.BeforeDelimiter(_, \" \", 1), type text}})",
                "in",
                "    #\"Extracted Text Before Delimiter\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Product",
            "lineageTag": "b1402714-05c2-43e6-a976-993681a9bc85",
            "levels": [
              {
                "name": "Category",
                "ordinal": 0,
                "column": "Category",
                "lineageTag": "7a68f025-e259-4a67-b4b7-6a36c09d87b9"
              },
              {
                "name": "SubCategory",
                "ordinal": 1,
                "column": "SubCategory",
                "lineageTag": "3dbb23ed-d60e-4489-bfa4-775f05dee92d"
              },
              {
                "name": "Brand",
                "ordinal": 2,
                "column": "Brand",
                "lineageTag": "0e59448a-2e48-425f-bb81-e1e5f680c5c8"
              },
              {
                "name": "ProductName",
                "ordinal": 3,
                "column": "ProductName",
                "lineageTag": "31429181-b35c-48fa-ad60-dade8e6aebe2"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "dim_region",
        "lineageTag": "b2b05a06-cd0e-49ef-b0f5-a3b68d6c0919",
        "columns": [
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "907c10e1-92bf-4135-b790-534820b48e56",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RegionName",
            "dataType": "string",
            "sourceColumn": "RegionName",
            "lineageTag": "ace170b7-2ab9-40ce-a605-51bedc13d9bc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RepresentativeCountry",
            "dataType": "string",
            "sourceColumn": "RepresentativeCountry",
            "lineageTag": "cca4bc55-6b21-4156-a003-2fd49caaba8d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Continent",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dim_region'[RegionName],\"North America\",\"America\",\"South America\",\"America\", \"Oceania\",\"Asia\",\"Africa\",\"Asia\",'dim_region'[RegionName])",
            "lineageTag": "a488a8e2-7327-4cbb-9b3e-9cd19209f820",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Country",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('dim_region'[RepresentativeCountry],\"Nigeria\",\"Japan\", \"United States\",\"USA\",'dim_region'[RepresentativeCountry])",
            "lineageTag": "60b7d6b3-7704-4c3e-999e-db471d544dbe",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_region",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\DIM\\dim_region.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"RegionID\", type text}, {\"RegionName\", type text}, {\"RepresentativeCountry\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_return_reason",
        "lineageTag": "113c9baf-a27b-426d-91d1-cce65b1289b2",
        "columns": [
          {
            "name": "ReturnReasonID",
            "dataType": "string",
            "sourceColumn": "ReturnReasonID",
            "lineageTag": "8389a82d-0a76-4017-a5d8-b407094f4529",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ReturnReason",
            "dataType": "string",
            "sourceColumn": "ReturnReason",
            "lineageTag": "791e41b4-d9cc-4cde-9945-e3d2edf4204a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_return_reason",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\DIM\\dim_return_reason.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ReturnReasonID\", type text}, {\"ReturnReason\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_orders",
        "lineageTag": "ed2d3a59-7f3d-4abf-98ac-e0c393723fe0",
        "columns": [
          {
            "name": "OrderID",
            "dataType": "string",
            "sourceColumn": "OrderID",
            "lineageTag": "afd8b56c-77ee-44f7-93a4-fb211b7a349f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Long Date",
            "lineageTag": "8c0b1898-f65d-482f-bc47-cb61b90c58f0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "251591be-9637-40f4-b16b-339c84411e57",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "2e55d7e4-95ec-4cca-82b5-459c4a61755c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "a5ecd894-c386-41f5-948f-e557cab5ae5a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderStatus",
            "dataType": "string",
            "sourceColumn": "OrderStatus",
            "lineageTag": "22101321-1d92-493c-89cb-e52256509f24",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderAmount",
            "dataType": "double",
            "sourceColumn": "OrderAmount",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4d4ce98d-0fb9-42a5-a239-ed09a1629b7d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "ShippingCost",
            "dataType": "double",
            "sourceColumn": "ShippingCost",
            "lineageTag": "722e3759-b66d-4130-ab60-b015f0a190bc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "DeliveryDays",
            "dataType": "int64",
            "sourceColumn": "DeliveryDays",
            "formatString": "0",
            "lineageTag": "1c88f350-934f-4f46-99ff-680554b064b0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "PaymentMethod",
            "dataType": "string",
            "sourceColumn": "PaymentMethod",
            "lineageTag": "0b2c3476-04f4-4829-af9b-8e39962f3555",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "OrderStatus (2)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "SWITCH('fact_orders'[OrderStatus],\"Pending\",\"In-Process\", \"Processing\",\"In-Process\",\"Returned\",\"Cancelled\",'fact_orders'[OrderStatus])",
            "lineageTag": "d534618b-76c5-473d-a723-749fd94f658d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Order_Value_Category_Col",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'fact_orders'[OrderAmount] < 50, \"Very Low\",",
              "    'fact_orders'[OrderAmount] >= 50 && 'fact_orders'[OrderAmount] < 100, \"Low\",",
              "    'fact_orders'[OrderAmount] >= 100 && 'fact_orders'[OrderAmount] < 250, \"Medium-Low\",",
              "    'fact_orders'[OrderAmount] >= 250 && 'fact_orders'[OrderAmount] < 500, \"Medium\",",
              "    'fact_orders'[OrderAmount] >= 500 && 'fact_orders'[OrderAmount] < 1000, \"Medium-High\",",
              "    'fact_orders'[OrderAmount] >= 1000 && 'fact_orders'[OrderAmount] < 2000, \"High\",",
              "    'fact_orders'[OrderAmount] >= 2000 && 'fact_orders'[OrderAmount] < 5000, \"Very High\",",
              "    'fact_orders'[OrderAmount] >= 5000, \"Premium\",",
              "    \"Other\"",
              ")",
              ""
            ],
            "lineageTag": "d1fae63a-5187-4c28-b5ee-abf17507e9bf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Order_Value_Category_Col_2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'fact_orders'[OrderAmount] < 50, \"Low Value\",",
              "    'fact_orders'[OrderAmount] >= 50 && 'fact_orders'[OrderAmount] < 250, \"Medium Value\",",
              "    'fact_orders'[OrderAmount] >= 250 && 'fact_orders'[OrderAmount] < 1000, \"High Value\",",
              "    'fact_orders'[OrderAmount] >= 1000, \"Very High Value\",",
              "    \"Other\"",
              ")",
              ""
            ],
            "lineageTag": "152eca1d-bdad-40c2-930d-76e340788b8c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Delivery On Time vs Delayed",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "    TRUE(),",
              "    'fact_orders'[DeliveryDays]<= 6, \"On-Time\", \"Delayed\"",
              ")"
            ],
            "lineageTag": "a7d6a337-2cc5-4ab5-b837-4871e898cc1c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_orders",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\DIM\\fact_orders.csv\"),[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"OrderID\", type text}, {\"OrderDate\", type date}, {\"CustomerID\", type text}, {\"ChannelID\", type text}, {\"RegionID\", type text}, {\"OrderStatus\", type text}, {\"OrderAmount\", type number}, {\"ShippingCost\", type number}, {\"DeliveryDays\", Int64.Type}, {\"PaymentMethod\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "number_of_orders",
            "expression": "DISTINCTCOUNT('fact_orders'[OrderID])",
            "formatString": "#,0",
            "lineageTag": "577617f3-baf0-470a-a9ca-9a697de956ae"
          },
          {
            "name": "curr_year_orders",
            "expression": [
              "VAR curr_year = Year(MAX('fact_orders'[OrderDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [number_of_orders],",
              "        YEAR('fact_orders'[OrderDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [number_of_orders],",
              "        YEAR('fact_orders'[OrderDate]) = curr_year-1",
              ")",
              "",
              "RETURN",
              "curr_year_ORDERS"
            ],
            "formatString": "0",
            "lineageTag": "a4f23be6-2086-4fff-8a00-2cfe9b2f9433"
          },
          {
            "name": "prev_year_orders",
            "expression": [
              "VAR curr_year = Year(MAX('fact_orders'[OrderDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [number_of_orders],",
              "        YEAR('fact_orders'[OrderDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [number_of_orders],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              ")",
              "",
              "RETURN",
              "prev_year_ORDERS"
            ],
            "formatString": "0",
            "lineageTag": "0f886b68-e050-4665-a97e-ddcec50e908a"
          },
          {
            "name": "orders YoY Change Text",
            "expression": [
              "",
              "VAR OrdersCY = [curr_year_orders]      -- current year sales",
              "VAR OrdersPY = [prev_year_orders]      -- previous year sales",
              "VAR Change = DIVIDE(OrdersCY - OrdersPY, OrdersPY)",
              "VAR Sign = ",
              "    IF(Change >= 0, \"+\", \"-\")",
              "RETURN",
              "Sign & FORMAT( ABS(Change), \"0.000\" )"
            ],
            "lineageTag": "72c7c2f7-a80d-4d72-86bb-8520fd609830"
          },
          {
            "name": "percentage_diff_prv_year_orders",
            "expression": [
              "",
              "VAR curr_year =",
              "    YEAR ( MAX ( 'fact_orders'[OrderDate] ) )",
              "",
              "VAR curr_year_orders =",
              "    CALCULATE (",
              "        [number_of_orders],",
              "        YEAR ( 'fact_orders'[OrderDate] ) = curr_year",
              "    )",
              "",
              "VAR prev_year_orders =",
              "    CALCULATE (",
              "        [number_of_orders],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              "    )",
              "",
              "VAR pct_change =",
              "    DIVIDE ( curr_year_orders - prev_year_orders, prev_year_orders )",
              "",
              "VAR sign =",
              "    IF ( pct_change > 0, \"+\", \"\" )   -- negative already has \"-\" automatically",
              "",
              "RETURN",
              "sign & FORMAT( pct_change, \"0.00%\" )",
              ""
            ],
            "lineageTag": "171c51a2-dc0f-4c15-8709-0449e995cc46"
          },
          {
            "name": "orders_growth_color_kpi_rule",
            "expression": [
              "IF(",
              "    [curr_year_orders]>[prev_year_orders],",
              "    \"Green\",",
              "    \"Red\"",
              "    )"
            ],
            "lineageTag": "b5ea0117-1a9d-49d4-b45a-883271c86b02"
          },
          {
            "name": "customers_growth_color_kpi_box_rule",
            "expression": [
              "",
              "IF(",
              "    [curr_year_customers] > [prev_year_customers],",
              "    \"#C6EFCE\",     -- light green",
              "    \"#FFC7CE\"      -- light red",
              ")"
            ],
            "lineageTag": "5aeda13a-636b-4a53-9fa1-c08802da2fa0"
          },
          {
            "name": "number_of_customers",
            "expression": "DISTINCTCOUNT('fact_orders'[CustomerID])",
            "formatString": "#,0",
            "lineageTag": "16a0475d-d08c-4f67-89cd-4695f6669a3b"
          },
          {
            "name": "percentage_diff_prv_year_customers",
            "expression": [
              "",
              "VAR curr_year =",
              "    YEAR ( MAX ( 'fact_orders'[OrderDate] ) )",
              "",
              "VAR curr_year_orders =",
              "    CALCULATE (",
              "        [number_of_customers],",
              "        YEAR ( 'fact_orders'[OrderDate] ) = curr_year",
              "    )",
              "",
              "VAR prev_year_orders =",
              "    CALCULATE (",
              "        [number_of_customers],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              "    )",
              "",
              "VAR pct_change =",
              "    DIVIDE ( curr_year_orders - prev_year_orders, prev_year_orders )",
              "",
              "VAR sign =",
              "    IF ( pct_change > 0, \"+\", \"\" )   -- negative already has \"-\" automatically",
              "",
              "RETURN",
              "sign & FORMAT( pct_change, \"0.00%\" )",
              ""
            ],
            "lineageTag": "acc3f1cf-884a-482f-9dc2-06dabe795b95"
          },
          {
            "name": "curr_year_customers",
            "expression": [
              "VAR curr_year = Year(MAX('fact_orders'[OrderDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [number_of_customers],",
              "        YEAR('fact_orders'[OrderDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [number_of_customers],",
              "        YEAR('fact_orders'[OrderDate]) = curr_year-1",
              ")",
              "",
              "RETURN",
              "curr_year_ORDERS"
            ],
            "formatString": "0",
            "lineageTag": "ed8884f6-02a9-42f2-a3bb-0deece2a84b1"
          },
          {
            "name": "prev_year_customers",
            "expression": [
              "VAR curr_year = Year(MAX('fact_orders'[OrderDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [number_of_customers],",
              "        YEAR('fact_orders'[OrderDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [number_of_customers],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              ")",
              "",
              "RETURN",
              "[prev_year_orders]"
            ],
            "formatString": "0",
            "lineageTag": "712bbc29-7b8d-4641-b8c2-36d693d4bf57"
          },
          {
            "name": "customers_growth_color_kpi_rule",
            "expression": [
              "IF(",
              "    [curr_year_customers]>[prev_year_customers],",
              "    \"Green\",",
              "    \"Red\"",
              "    )"
            ],
            "lineageTag": "9b7e0879-1447-4479-a3da-6be42223c5a6"
          },
          {
            "name": "customers YoY Change Text",
            "expression": [
              "",
              "VAR OrdersCY = [curr_year_customers]      -- current year sales",
              "VAR OrdersPY = [prev_year_customers]      -- previous year sales",
              "VAR Change = DIVIDE(OrdersCY - OrdersPY, OrdersPY)",
              "VAR Sign = ",
              "    IF(Change >= 0, \"+\", \"-\")",
              "RETURN",
              "Sign & FORMAT( ABS(Change), \"0.000\" )"
            ],
            "lineageTag": "35a83c59-5a63-4d84-96fe-7a6825e7d576"
          },
          {
            "name": "Customer Churn Rate (%)",
            "expression": [
              "",
              "VAR CurrYearCustomers =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        ALL('dim_date'),",
              "        KEEPFILTERS('dim_date'),",
              "        VALUES('dim_date'[Year])     -- current slicer selection",
              "    )",
              "",
              "VAR PrevYearCustomers =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD('dim_date'[Date], -1, YEAR)",
              "    )",
              "",
              "VAR LostCustomers =",
              "    COUNTROWS(",
              "        EXCEPT(PrevYearCustomers, CurrYearCustomers)",
              "    )",
              "",
              "VAR StartOfYearCustomers =",
              "    COUNTROWS(PrevYearCustomers)",
              "",
              "RETURN",
              "    DIVIDE(LostCustomers, StartOfYearCustomers)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2fc6af54-1828-4061-b37a-b934d4c9848e"
          },
          {
            "name": "Returning Customers",
            "expression": [
              "",
              "---------------------------------------------",
              "-- Customers in current period",
              "---------------------------------------------",
              "VAR CurrCust =",
              "    VALUES ( 'fact_orders'[CustomerID] )",
              "",
              "-- Customers in prior period (e.g., last year)",
              "VAR Prev1_Cust =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( 'dim_date'[Date], -1, YEAR )",
              "    )",
              "",
              "-- Customers in prior-2 period (two years ago)",
              "VAR Prev2_Cust =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( 'dim_date'[Date], -2, YEAR )",
              "    )",
              "",
              "---------------------------------------------",
              "-- Returning customers = bought 2 years ago,",
              "-- skipped last year, bought this period",
              "---------------------------------------------",
              "VAR ReturningCust =",
              "    INTERSECT (",
              "        Prev2_Cust,              -- bought 2 years ago",
              "        EXCEPT ( CurrCust, Prev1_Cust )  -- bought this period but NOT last period",
              "    )",
              "",
              "RETURN",
              "    COUNTROWS ( ReturningCust )"
            ],
            "formatString": "0",
            "lineageTag": "2493a391-adf1-46cd-9065-19060948acbf"
          },
          {
            "name": "New Customers",
            "expression": [
              "",
              "VAR CurrYear =",
              "    SELECTEDVALUE ( 'dim_date'[Year] )",
              "",
              "VAR PrevYear =",
              "    CurrYear - 1",
              "",
              "-- Customers who bought in previous year",
              "VAR Cust_PrevYear =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        'dim_date'[Year] = PrevYear",
              "    )",
              "",
              "-- Customers who bought in current year",
              "VAR Cust_CurrYear =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        'dim_date'[Year] = CurrYear",
              "    )",
              "",
              "-- New customers = customers in current year",
              "-- who were NOT customers in previous year",
              "VAR NewCust =",
              "    EXCEPT ( Cust_CurrYear, Cust_PrevYear )",
              "",
              "RETURN",
              "    COUNTROWS ( NewCust )",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "0bf12359-53d8-4057-98e7-b64e3af611f6"
          },
          {
            "name": "avg_revenue_per_customer",
            "expression": "SUM('fact_orders'[OrderAmount]) / [number_of_customers]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "685691b5-7616-4004-a701-51def70b1f15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Customer_MoM_Diff",
            "expression": [
              "VAR Curr = [number_of_customers]",
              "VAR Prev =",
              "    CALCULATE (",
              "        [number_of_customers],",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR Diff = Curr - Prev",
              "VAR DiffPct = DIVIDE ( Diff, Prev )",
              "",
              "-- Only add + if positive, otherwise nothing",
              "VAR PlusSymbol = IF ( Diff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    -- Diff shows negative automatically if < 0",
              "    FORMAT ( Diff, \"#,##0\" )",
              "        & \"  |  \"",
              "        & PlusSymbol & FORMAT ( DiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "951849d2-9465-4317-b570-b94e6303c372"
          },
          {
            "name": "Customer_MoM_Color",
            "expression": [
              "VAR Curr =",
              "    [number_of_customers]",
              "VAR Prev =",
              "    CALCULATE(",
              "        [number_of_customers],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "VAR Diff = Curr - Prev",
              "RETURN",
              "IF( Diff > 0, \"#00B050\", \"#FF0000\" )"
            ],
            "lineageTag": "5016d7e4-3621-4be2-a490-066cb6b414a5"
          },
          {
            "name": "New_Customers_MoM_Diff",
            "expression": [
              "",
              "VAR CurrentCustomers =",
              "    VALUES ( 'fact_orders'[CustomerID] )",
              "",
              "VAR PriorCustomers =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( 'dim_date'[Date], -1, YEAR )",
              "    )",
              "",
              "VAR NewCurr =",
              "    COUNTROWS ( EXCEPT ( CurrentCustomers, PriorCustomers ) )",
              "",
              "VAR PrevPeriodCustomers =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR PrevPeriodCustomers_Prior =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( SAMEPERIODLASTYEAR ( 'dim_date'[Date] ), -1, YEAR )",
              "    )",
              "",
              "VAR NewPrev =",
              "    COUNTROWS ( EXCEPT ( PrevPeriodCustomers, PrevPeriodCustomers_Prior ) )",
              "",
              "VAR Diff = NewCurr - NewPrev",
              "VAR DiffPct = DIVIDE( Diff, NewPrev )",
              "",
              "VAR Plus = IF( Diff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    FORMAT( Diff, \"#,##0\" )",
              "        & \"  |  \"",
              "        & Plus & FORMAT( DiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "d7d06170-3009-46d9-8c9e-c509505150f7"
          },
          {
            "name": "New_Customers_MoM_Color",
            "expression": [
              "",
              "VAR CurrentCustomers =",
              "    VALUES ( 'fact_orders'[CustomerID] )",
              "",
              "VAR PriorCustomers =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( 'dim_date'[Date], -1, YEAR )",
              "    )",
              "",
              "VAR NewCurr =",
              "    COUNTROWS ( EXCEPT ( CurrentCustomers, PriorCustomers ) )",
              "",
              "VAR PrevPeriodCustomers =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR PrevPeriodCustomers_Prior =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( SAMEPERIODLASTYEAR ( 'dim_date'[Date] ), -1, YEAR )",
              "    )",
              "",
              "VAR NewPrev =",
              "    COUNTROWS ( EXCEPT ( PrevPeriodCustomers, PrevPeriodCustomers_Prior ) )",
              "",
              "VAR Diff = NewCurr - NewPrev",
              "RETURN",
              "IF( Diff > 0, \"#00B050\", \"#FF0000\" )",
              ""
            ],
            "lineageTag": "a4b0c2ad-5dec-4df8-bbe4-4976b2fb3e0c"
          },
          {
            "name": "Returning_Customers_MoM_Diff",
            "expression": [
              "VAR CurrCust = VALUES( 'fact_orders'[CustomerID] )",
              "VAR Prev1_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( 'dim_date'[Date], -1, YEAR )",
              "    )",
              "VAR Prev2_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( 'dim_date'[Date], -2, YEAR )",
              "    )",
              "VAR ReturningCurr =",
              "    COUNTROWS(",
              "        INTERSECT(",
              "            Prev2_Cust,",
              "            EXCEPT( CurrCust, Prev1_Cust )",
              "        )",
              "    )",
              "",
              "VAR PY_CurrCust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        SAMEPERIODLASTYEAR( 'dim_date'[Date] )",
              "    )",
              "VAR PY_Prev1_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( SAMEPERIODLASTYEAR( 'dim_date'[Date] ), -1, YEAR )",
              "    )",
              "VAR PY_Prev2_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( SAMEPERIODLASTYEAR( 'dim_date'[Date] ), -2, YEAR )",
              "    )",
              "VAR ReturningPrev =",
              "    COUNTROWS(",
              "        INTERSECT(",
              "            PY_Prev2_Cust,",
              "            EXCEPT( PY_CurrCust, PY_Prev1_Cust )",
              "        )",
              "    )",
              "",
              "VAR Diff = ReturningCurr - ReturningPrev",
              "VAR DiffPct = DIVIDE( Diff, ReturningPrev )",
              "VAR Plus = IF( Diff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    FORMAT( Diff, \"#,##0\" )",
              "        & \"  |  \"",
              "        & Plus & FORMAT( DiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "e6eeb921-486b-4c2c-ab3c-61bc68f53e01"
          },
          {
            "name": "Returning_Customers_MoM_Color",
            "expression": [
              "",
              "VAR CurrCust = VALUES( 'fact_orders'[CustomerID] )",
              "VAR Prev1_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( 'dim_date'[Date], -1, YEAR )",
              "    )",
              "VAR Prev2_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( 'dim_date'[Date], -2, YEAR )",
              "    )",
              "VAR ReturningCurr =",
              "    COUNTROWS(",
              "        INTERSECT(",
              "            Prev2_Cust,",
              "            EXCEPT( CurrCust, Prev1_Cust )",
              "        )",
              "    )",
              "",
              "VAR PY_CurrCust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        SAMEPERIODLASTYEAR( 'dim_date'[Date] )",
              "    )",
              "VAR PY_Prev1_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( SAMEPERIODLASTYEAR( 'dim_date'[Date] ), -1, YEAR )",
              "    )",
              "VAR PY_Prev2_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( SAMEPERIODLASTYEAR( 'dim_date'[Date] ), -2, YEAR )",
              "    )",
              "VAR ReturningPrev =",
              "    COUNTROWS(",
              "        INTERSECT(",
              "            PY_Prev2_Cust,",
              "            EXCEPT( PY_CurrCust, PY_Prev1_Cust )",
              "        )",
              "    )",
              "",
              "VAR Diff = ReturningCurr - ReturningPrev",
              "RETURN IF( Diff > 0, \"#00B050\", \"#FF0000\" )"
            ],
            "lineageTag": "2cf42e54-66b9-4e1e-9b22-c09ea6c78940"
          },
          {
            "name": "Customer_Churn_MoM_Diff",
            "expression": [
              "VAR CurrCust = VALUES('fact_orders'[CustomerID])",
              "VAR PrevCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD('dim_date'[Date], -1, YEAR)",
              "    )",
              "VAR RetainedCurr = COUNTROWS(INTERSECT(CurrCust, PrevCust))",
              "VAR TotalPrevCust = COUNTROWS(PrevCust)",
              "VAR RetentionCurr = DIVIDE(RetainedCurr, TotalPrevCust)",
              "",
              "VAR PY_CurrCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "VAR PY_PrevCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD(SAMEPERIODLASTYEAR('dim_date'[Date]), -1, YEAR)",
              "    )",
              "VAR RetainedPrev = COUNTROWS(INTERSECT(PY_CurrCust, PY_PrevCust))",
              "VAR TotalPrevPrev = COUNTROWS(PY_PrevCust)",
              "VAR RetentionPrev = DIVIDE(RetainedPrev, TotalPrevPrev)",
              "",
              "VAR Diff = RetentionCurr - RetentionPrev",
              "VAR Plus = IF(Diff > 0, \"+\", \"\")",
              "",
              "RETURN",
              "Plus & FORMAT(Diff, \"0%\") & \" vs PY\""
            ],
            "lineageTag": "707c52b1-53cd-466f-a58e-223d7e1006df"
          },
          {
            "name": "%_of_completed_orders",
            "expression": [
              "VAR completed_orders = CALCULATE(",
              "    [number_of_orders],",
              "'fact_orders'[OrderStatus] = \"Delivered\"",
              ")",
              "RETURN",
              "DIVIDE(completed_orders,[number_of_orders])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "43ea76c1-3d5b-423b-ab72-17cbf063b763"
          },
          {
            "name": "%_of_cancelled_orders",
            "expression": [
              "VAR cancelled_orders = CALCULATE(",
              "    [number_of_orders],",
              "'fact_orders'[OrderStatus] = \"Cancelled\"",
              ")",
              "RETURN",
              "DIVIDE(cancelled_orders,[number_of_orders])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6a3d0871-f0f7-4177-aa41-d1bd8d47a605"
          },
          {
            "name": "Customer_Retention_Rate",
            "expression": [
              "",
              "VAR CurrYearCustomers =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        ALL('dim_date'),",
              "        KEEPFILTERS('dim_date'),",
              "        VALUES('dim_date'[Year])   -- current slicer selection",
              "    )",
              "",
              "VAR PrevYearCustomers =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD('dim_date'[Date], -1, YEAR)",
              "    )",
              "",
              "-- Customers who bought both last year AND this year",
              "VAR RetainedCustomers =",
              "    COUNTROWS(",
              "        INTERSECT(PrevYearCustomers, CurrYearCustomers)",
              "    )",
              "",
              "-- Total customers last year",
              "VAR TotalPrevYearCustomers =",
              "    COUNTROWS(PrevYearCustomers)",
              "",
              "RETURN",
              "    DIVIDE(RetainedCustomers, TotalPrevYearCustomers)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2e0ba392-f771-4ecd-9249-ba47918f0524"
          },
          {
            "name": "Customer_Retention_YoY_Color",
            "expression": [
              "",
              "VAR CurrCust = VALUES('fact_orders'[CustomerID])",
              "VAR PrevCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD('dim_date'[Date], -1, YEAR)",
              "    )",
              "VAR RetainedCurr = COUNTROWS(INTERSECT(CurrCust, PrevCust))",
              "VAR TotalPrevCust = COUNTROWS(PrevCust)",
              "VAR RetentionCurr = DIVIDE(RetainedCurr, TotalPrevCust)",
              "",
              "VAR PY_CurrCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "VAR PY_PrevCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD(SAMEPERIODLASTYEAR('dim_date'[Date]), -1, YEAR)",
              "    )",
              "VAR RetainedPrev = COUNTROWS(INTERSECT(PY_CurrCust, PY_PrevCust))",
              "VAR TotalPrevPrev = COUNTROWS(PY_PrevCust)",
              "VAR RetentionPrev = DIVIDE(RetainedPrev, TotalPrevPrev)",
              "",
              "VAR Diff = RetentionCurr - RetentionPrev",
              "RETURN IF(Diff > 0, \"#00B050\", \"#FF0000\")"
            ],
            "lineageTag": "a70fb1e1-857c-43c3-9b9e-699905169f6b"
          },
          {
            "name": "Number_of_Orders_YoY_Color",
            "expression": [
              "",
              "VAR CurrOrders = DISTINCTCOUNT('fact_orders'[OrderID])",
              "VAR PrevOrders = CALCULATE(DISTINCTCOUNT('fact_orders'[OrderID]), SAMEPERIODLASTYEAR('dim_date'[Date]))",
              "RETURN",
              "IF(CurrOrders > PrevOrders, \"Green\", \"Red\")"
            ],
            "lineageTag": "ba5b8732-7035-4743-b5f2-ec5668c648bd"
          },
          {
            "name": "Number_of_Orders_YoY_Diff",
            "expression": [
              "VAR CurrOrders =",
              "    DISTINCTCOUNT('fact_orders'[OrderID])",
              "",
              "VAR PrevOrders =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR Diff = CurrOrders - PrevOrders",
              "VAR DiffPct = DIVIDE(Diff, PrevOrders)",
              "",
              "VAR PlusPct = IF(DiffPct > 0, \"+\", \"\")",
              "",
              "RETURN",
              "FORMAT(Diff, \"#,##0\")",
              "    & \" | \"",
              "    & PlusPct & FORMAT(DiffPct, \"0.00%\")",
              "    & \" vs PY\""
            ],
            "lineageTag": "088be450-a4ab-47a1-b07f-8cca864756fc"
          },
          {
            "name": "Avg_Order_Value_YoY_Color",
            "expression": [
              "",
              "VAR CurrAOV = SUM('fact_sales'[NetSales]) / DISTINCTCOUNT('fact_orders'[OrderID])",
              "VAR PrevAOV = ",
              "    CALCULATE(",
              "        SUM('fact_sales'[NetSales]) / DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "RETURN",
              "IF(CurrAOV > PrevAOV, \"#00B050\", \"#FF0000\")",
              ""
            ],
            "lineageTag": "a081a351-93aa-4293-9d30-5b04ba1b2710"
          },
          {
            "name": "Avg_Order_Value_YoY_Diff",
            "expression": [
              "",
              "VAR CurrAOV =",
              "    DIVIDE(",
              "        SUM('fact_sales'[NetSales]),",
              "        DISTINCTCOUNT('fact_orders'[OrderID])",
              "    )",
              "",
              "VAR PrevAOV =",
              "    CALCULATE(",
              "        DIVIDE(",
              "            SUM('fact_sales'[NetSales]),",
              "            DISTINCTCOUNT('fact_orders'[OrderID])",
              "        ),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR Diff = CurrAOV - PrevAOV",
              "VAR DiffPct = DIVIDE(Diff, PrevAOV)",
              "",
              "-- Detect if negative",
              "VAR SignAmt = IF(Diff < 0, \"-\", \"\")",
              "",
              "-- Absolute amount for formatting",
              "VAR AbsDiff = ABS(Diff)",
              "",
              "VAR PlusPct = IF(DiffPct > 0, \"+\", \"\")",
              "",
              "RETURN",
              "SignAmt & \"$\" & FORMAT(AbsDiff, \"#,##0.00\")",
              "    & \" | \"",
              "    & PlusPct & FORMAT(DiffPct, \"0%\")",
              "    & \" vs PY\""
            ],
            "lineageTag": "6d643856-0e73-4fb2-893b-c0714d19da6a"
          },
          {
            "name": "Completed_Orders_YoY_Diff",
            "expression": [
              "VAR CurrCompleted =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Delivered\"",
              "    )",
              "",
              "VAR CurrTotal =",
              "    DISTINCTCOUNT('fact_orders'[OrderID])",
              "",
              "VAR CurrPct =",
              "    DIVIDE(CurrCompleted, CurrTotal)",
              "",
              "VAR PrevCompleted =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Delivered\",",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevTotal =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevPct =",
              "    DIVIDE(PrevCompleted, PrevTotal)",
              "",
              "VAR Diff = CurrPct - PrevPct",
              "",
              "RETURN",
              "FORMAT(Diff, \"0.00%\") & \" vs PY\""
            ],
            "lineageTag": "b19b0750-418f-4f14-96e6-4bc9653dc912"
          },
          {
            "name": "Completed_Orders_YoY_Color",
            "expression": [
              "",
              "---------------------------------------------",
              "-- Current period",
              "---------------------------------------------",
              "VAR CurrCompleted = CALCULATE(",
              "    DISTINCTCOUNT('fact_orders'[OrderID]),",
              "    'fact_orders'[OrderStatus] = \"Delivered\"",
              ")",
              "VAR CurrTotal = DISTINCTCOUNT('fact_orders'[OrderID])",
              "VAR CurrPct = DIVIDE(CurrCompleted, CurrTotal)",
              "",
              "---------------------------------------------",
              "-- Previous year's equivalent period",
              "---------------------------------------------",
              "VAR PrevCompleted = CALCULATE(",
              "    DISTINCTCOUNT('fact_orders'[OrderID]),",
              "    'fact_orders'[OrderStatus] = \"Delivered\",",
              "    SAMEPERIODLASTYEAR('dim_date'[Date])",
              ")",
              "VAR PrevTotal = CALCULATE(",
              "    DISTINCTCOUNT('fact_orders'[OrderID]),",
              "    SAMEPERIODLASTYEAR('dim_date'[Date])",
              ")",
              "VAR PrevPct = DIVIDE(PrevCompleted, PrevTotal)",
              "",
              "---------------------------------------------",
              "-- Return Color",
              "---------------------------------------------",
              "RETURN",
              "IF(CurrPct > PrevPct, \"Green\", \"Red\")"
            ],
            "lineageTag": "aa14bd88-bc12-43d2-9fda-3ba89d5eda99"
          },
          {
            "name": "Cancelled_Orders_YoY_Diff",
            "expression": [
              "VAR CurrCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\"",
              "    )",
              "",
              "VAR CurrTotal =",
              "    DISTINCTCOUNT('fact_orders'[OrderID])",
              "",
              "VAR CurrPct =",
              "    DIVIDE(CurrCancelled, CurrTotal)",
              "",
              "VAR PrevCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\",",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevTotal =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevPct =",
              "    DIVIDE(PrevCancelled, PrevTotal)",
              "",
              "VAR Diff = CurrPct - PrevPct",
              "",
              "RETURN",
              "FORMAT(Diff, \"0.00%\") & \" vs PY\""
            ],
            "lineageTag": "bb2a5a8c-f2d9-4b42-b33f-f3502f652e82"
          },
          {
            "name": "Cancelled_Orders_YoY_Color",
            "expression": [
              "VAR CurrCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\"",
              "    )",
              "",
              "VAR PrevCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\",",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "RETURN",
              "IF(CurrCancelled < PrevCancelled, \"#00B050\", \"#FF0000\")"
            ],
            "lineageTag": "1b2c8063-b730-4c6a-bfbe-767da479c280"
          },
          {
            "name": "Avg. Delivery Time (Days)",
            "expression": [
              "VAR deliverytime =AVERAGE('fact_orders'[DeliveryDays])",
              "RETURN FORMAT(deliverytime,\"0.00\") & \" Days\""
            ],
            "lineageTag": "4b00f1e1-8737-43c3-91ba-7f6b273b3ccc"
          },
          {
            "name": "Avg. Target Delivery Time (Days)",
            "expression": "4",
            "formatString": "0",
            "lineageTag": "9affa23e-3fe9-46b3-a88a-d59178f8d146"
          },
          {
            "name": "Measure",
            "lineageTag": "362aca22-a12a-424a-b25d-1ebed0dc10c1",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ]
          },
          {
            "name": "On-Time Delivery Rate",
            "expression": [
              "VAR ontimeorders = CALCULATE(",
              "    COUNT(",
              "        'fact_orders'[OrderID]),",
              "        'fact_orders'[Delivery On Time vs Delayed] = \"On-Time\")",
              "        RETURN",
              "        DIVIDE(ontimeorders,[number_of_orders])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bc348829-300c-480f-8026-87559029b9d7"
          },
          {
            "name": "Customer_MoM_Arrow",
            "expression": [
              "",
              "VAR Curr = [number_of_customers]",
              "VAR Prev =",
              "    CALCULATE (",
              "        [number_of_customers],",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR Diff = Curr - Prev",
              "RETURN IF ( Diff > 0, \"\", \"\" )",
              ""
            ],
            "lineageTag": "52c1a86a-8fa1-41ed-be69-66110a97a095"
          },
          {
            "name": "New_Customers_MoM_Arrow",
            "expression": [
              "",
              "VAR CurrentCustomers =",
              "    VALUES ( 'fact_orders'[CustomerID] )",
              "",
              "VAR PriorCustomers =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( 'dim_date'[Date], -1, YEAR )",
              "    )",
              "",
              "VAR NewCurr =",
              "    COUNTROWS ( EXCEPT ( CurrentCustomers, PriorCustomers ) )",
              "",
              "VAR PrevPeriodCustomers =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR PrevPeriodCustomers_Prior =",
              "    CALCULATETABLE (",
              "        VALUES ( 'fact_orders'[CustomerID] ),",
              "        DATEADD ( SAMEPERIODLASTYEAR ( 'dim_date'[Date] ), -1, YEAR )",
              "    )",
              "",
              "VAR NewPrev =",
              "    COUNTROWS ( EXCEPT ( PrevPeriodCustomers, PrevPeriodCustomers_Prior ) )",
              "",
              "VAR Diff = NewCurr - NewPrev",
              "RETURN",
              "IF( Diff > 0, \"\", \"\" )",
              ""
            ],
            "lineageTag": "85009c96-c78d-4fcb-9fe7-c79bea1dea5d"
          },
          {
            "name": "Returning_Customers_MoM_Arrow",
            "expression": [
              "",
              "VAR CurrCust = VALUES( 'fact_orders'[CustomerID] )",
              "VAR Prev1_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( 'dim_date'[Date], -1, YEAR )",
              "    )",
              "VAR Prev2_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( 'dim_date'[Date], -2, YEAR )",
              "    )",
              "VAR ReturningCurr =",
              "    COUNTROWS(",
              "        INTERSECT(",
              "            Prev2_Cust,",
              "            EXCEPT( CurrCust, Prev1_Cust )",
              "        )",
              "    )",
              "",
              "VAR PY_CurrCust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        SAMEPERIODLASTYEAR( 'dim_date'[Date] )",
              "    )",
              "VAR PY_Prev1_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( SAMEPERIODLASTYEAR( 'dim_date'[Date] ), -1, YEAR )",
              "    )",
              "VAR PY_Prev2_Cust =",
              "    CALCULATETABLE(",
              "        VALUES( 'fact_orders'[CustomerID] ),",
              "        DATEADD( SAMEPERIODLASTYEAR( 'dim_date'[Date] ), -2, YEAR )",
              "    )",
              "VAR ReturningPrev =",
              "    COUNTROWS(",
              "        INTERSECT(",
              "            PY_Prev2_Cust,",
              "            EXCEPT( PY_CurrCust, PY_Prev1_Cust )",
              "        )",
              "    )",
              "",
              "VAR Diff = ReturningCurr - ReturningPrev",
              "RETURN IF( Diff > 0, \"\", \"\" )",
              ""
            ],
            "lineageTag": "49b089cf-6a8c-480b-a459-dc7040562be1"
          },
          {
            "name": "Customer_Churn_MoM_Arrow",
            "expression": [
              "",
              "VAR CurrCust = VALUES('fact_orders'[CustomerID])",
              "VAR PrevCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD('dim_date'[Date], -1, YEAR)",
              "    )",
              "VAR RetainedCurr = COUNTROWS(INTERSECT(CurrCust, PrevCust))",
              "VAR TotalPrevCust = COUNTROWS(PrevCust)",
              "VAR RetentionCurr = DIVIDE(RetainedCurr, TotalPrevCust)",
              "",
              "VAR PY_CurrCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "VAR PY_PrevCust =",
              "    CALCULATETABLE(",
              "        VALUES('fact_orders'[CustomerID]),",
              "        DATEADD(SAMEPERIODLASTYEAR('dim_date'[Date]), -1, YEAR)",
              "    )",
              "VAR RetainedPrev = COUNTROWS(INTERSECT(PY_CurrCust, PY_PrevCust))",
              "VAR TotalPrevPrev = COUNTROWS(PY_PrevCust)",
              "VAR RetentionPrev = DIVIDE(RetainedPrev, TotalPrevPrev)",
              "",
              "VAR Diff = RetentionCurr - RetentionPrev",
              "RETURN IF(Diff > 0, \"\", \"\")",
              ""
            ],
            "lineageTag": "56927776-970e-467e-899f-373b9e4ffe0b"
          },
          {
            "name": "Number_of_Orders_YoY_Arrow",
            "expression": [
              "",
              "VAR CurrOrders =",
              "    DISTINCTCOUNT('fact_orders'[OrderID])",
              "",
              "VAR PrevOrders =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR Diff = CurrOrders - PrevOrders",
              "",
              "RETURN IF(Diff > 0, \"\", \"\")",
              ""
            ],
            "lineageTag": "57e983d2-568a-46b2-bd5c-a07d8b1ea2e5"
          },
          {
            "name": "AOV_YoY_Arrow",
            "expression": [
              "",
              "VAR CurrAOV =",
              "    DIVIDE(",
              "        SUM('fact_sales'[NetSales]),",
              "        DISTINCTCOUNT('fact_orders'[OrderID])",
              "    )",
              "",
              "VAR PrevAOV =",
              "    CALCULATE(",
              "        DIVIDE(",
              "            SUM('fact_sales'[NetSales]),",
              "            DISTINCTCOUNT('fact_orders'[OrderID])",
              "        ),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR Diff = CurrAOV - PrevAOV",
              "RETURN",
              "IF( Diff > 0, \"\", \"\" )",
              ""
            ],
            "lineageTag": "c27d6653-3efa-4646-8baa-6260881436cd"
          },
          {
            "name": "Completed_Orders_YoY_Arrow",
            "expression": [
              "",
              "VAR CurrCompleted =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Delivered\"",
              "    )",
              "",
              "VAR CurrTotal =",
              "    DISTINCTCOUNT('fact_orders'[OrderID])",
              "",
              "VAR CurrPct = DIVIDE(CurrCompleted, CurrTotal)",
              "",
              "VAR PrevCompleted =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Delivered\",",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevTotal =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevPct = DIVIDE(PrevCompleted, PrevTotal)",
              "",
              "VAR Diff = CurrPct - PrevPct",
              "",
              "RETURN",
              "IF(Diff > 0, \"\", \"\")",
              ""
            ],
            "lineageTag": "5f7863b3-02ad-468f-8601-23bc306af2e5"
          },
          {
            "name": "Cancelled_Orders_YoY_Arrow_Color",
            "expression": [
              "",
              "VAR CurrCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\"",
              "    )",
              "",
              "VAR CurrTotal =",
              "    DISTINCTCOUNT('fact_orders'[OrderID])",
              "",
              "VAR CurrPct =",
              "    DIVIDE(CurrCancelled, CurrTotal)",
              "",
              "VAR PrevCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\",",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevTotal =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR PrevPct =",
              "    DIVIDE(PrevCancelled, PrevTotal)",
              "",
              "VAR Diff = CurrPct - PrevPct",
              "",
              "RETURN",
              "IF(Diff > 0, \"\", \"\")"
            ],
            "lineageTag": "70fb9f04-13c3-41e9-822e-a075178af357"
          },
          {
            "name": "Measure 2",
            "lineageTag": "d1669a3f-1b3e-4151-9eff-1e2a980fd004",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ]
          },
          {
            "name": "Cancelled_Orders_Color",
            "expression": [
              "",
              "VAR CurrCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\"",
              "    )",
              "",
              "VAR PrevCancelled =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('fact_orders'[OrderID]),",
              "        'fact_orders'[OrderStatus] = \"Cancelled\",",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "RETURN",
              "IF(CurrCancelled < PrevCancelled, \"#00B050\", \"#FF0000\")"
            ],
            "lineageTag": "21b52a39-de8f-4ac0-afe1-a936bd01de53"
          },
          {
            "name": "Order Amount Difference Text",
            "expression": [
              "",
              "VAR CurrentSales = SUM(fact_orders[orderamount])",
              "VAR PriorSales =",
              "    CALCULATE(",
              "        SUM(fact_orders[orderamount]),",
              "        SAMEPERIODLASTYEAR('dim_date'[date])",
              "    )",
              "VAR SalesDifference = CurrentSales - PriorSales",
              "",
              "RETURN",
              "    FORMAT(",
              "        SalesDifference,",
              "        \"+$#,##0;-$#,##0;$#,##0\"",
              "    )"
            ],
            "lineageTag": "7c3adda2-2e66-4277-8b7d-5c97996f7989"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_sales",
        "lineageTag": "ccb692f1-5575-4741-a555-57fc8e4babdf",
        "columns": [
          {
            "name": "SalesID",
            "dataType": "string",
            "sourceColumn": "SalesID",
            "lineageTag": "04efea54-3047-4c8e-a132-3855c7091d21",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderID",
            "dataType": "string",
            "sourceColumn": "OrderID",
            "lineageTag": "15c36bea-55bb-40a5-ba1c-b9fbcda9bace",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "lineageTag": "2b569856-0dd8-44e8-a627-5ee10e43ad21",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QuantitySold",
            "dataType": "int64",
            "sourceColumn": "QuantitySold",
            "formatString": "0",
            "lineageTag": "3fb52d87-b171-44c1-888a-a078d5d31be3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice",
            "lineageTag": "bcccedcc-7383-4532-82ca-0a1a2dbcc6ef",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "double",
            "sourceColumn": "Discount",
            "lineageTag": "c4821523-2d56-42bb-8f3f-ed17450c04f1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "COGS",
            "dataType": "double",
            "sourceColumn": "COGS",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "9f87e8e9-72c3-494e-9df5-a3ba21da4301",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "GrossProfit",
            "dataType": "double",
            "sourceColumn": "GrossProfit",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "e1b9a617-f3e4-4ca7-93ab-1fc984b62f39",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "SalesDate",
            "dataType": "dateTime",
            "sourceColumn": "SalesDate",
            "formatString": "Long Date",
            "lineageTag": "f750eec6-80d3-4275-a837-b6808e5cd719",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "cb6aaa29-bb63-4eb7-8f23-1d7276a307e5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "88fe4b42-02c6-4620-a86d-512e3df2977d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NetSales",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": [
              "VAR GrossSales = 'fact_sales'[QuantitySold] * 'fact_sales'[UnitPrice]",
              "RETURN GrossSales - 'fact_sales'[Discount] "
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "5dcf6008-53c3-44c9-9057-386dc867938f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "GrossSales",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "'fact_sales'[QuantitySold] * 'fact_sales'[UnitPrice]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c403b5e4-3750-4368-a0c0-d6b90e9c650d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_sales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\DIM\\fact_sales.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesID\", type text}, {\"OrderID\", type text}, {\"ProductID\", type text}, {\"QuantitySold\", Int64.Type}, {\"UnitPrice\", type number}, {\"Discount\", type number}, {\"COGS\", type number}, {\"GrossProfit\", type number}, {\"SalesDate\", type date}, {\"ChannelID\", type text}, {\"RegionID\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "percentage_diff_prv_year_sales",
            "expression": [
              "",
              "VAR curr_year =",
              "    YEAR ( MAX ( 'fact_sales'[SalesDate] ) )",
              "",
              "VAR curr_year_sales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[NetSales] ),",
              "        YEAR ( 'fact_sales'[SalesDate] ) = curr_year",
              "    )",
              "",
              "VAR prev_year_sales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[NetSales] ),",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              "    )",
              "",
              "VAR pct_change =",
              "    DIVIDE ( curr_year_sales - prev_year_sales, prev_year_sales )",
              "",
              "VAR sign =",
              "    IF ( pct_change > 0, \"+\", \"\" )   -- negative already has \"-\" automatically",
              "",
              "RETURN",
              "sign & FORMAT( pct_change, \"0.0%\" )",
              ""
            ],
            "lineageTag": "ead0e184-77be-4a9f-ae5f-99b5c36cb712"
          },
          {
            "name": "curr_year_sales",
            "expression": [
              "VAR curr_year = Year(MAX('fact_sales'[SalesDate]))",
              "var curr_year_sales = CALCULATE(",
              "    SUM(",
              "        'fact_sales'[NetSales]),",
              "        YEAR('fact_sales'[SalesDate]) = curr_year",
              ")",
              "",
              "var prev_year_sales = CALCULATE(",
              "    SUM(",
              "        'fact_sales'[NetSales]),",
              "        YEAR('fact_sales'[SalesDate]) = curr_year -1",
              ")",
              "",
              "RETURN",
              "curr_year_sales"
            ],
            "lineageTag": "eb4bb721-2ed6-4b46-a2af-75a2245676b9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "prev_year_sales",
            "expression": [
              "VAR curr_year = Year(MAX('fact_sales'[SalesDate]))",
              "var curr_year_sales = CALCULATE(",
              "    SUM(",
              "        'fact_sales'[NetSales]),",
              "        YEAR('fact_sales'[SalesDate]) = curr_year",
              ")",
              "",
              "var prev_year_sales = CALCULATE(",
              "    SUM(",
              "        'fact_sales'[NetSales]),",
              "       DATEADD('dim_date'[Date],-1,YEAR)",
              ")",
              "",
              "RETURN",
              "prev_year_sales"
            ],
            "lineageTag": "9eb626a7-0eb1-4ecc-b04c-9ff81b70024a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "sales_growth_color_kpi_rule",
            "expression": [
              "IF(",
              "    [curr_year_sales]>[prev_year_sales],",
              "    \"Green\",",
              "    \"Red\"",
              "    )"
            ],
            "lineageTag": "67874eba-822f-473a-81be-74455df88252"
          },
          {
            "name": "sales_growth_color_kpi_box_rule",
            "expression": [
              "",
              "IF(",
              "    [curr_year_sales] > [prev_year_sales],",
              "    \"#C6EFCE\",     -- light green",
              "    \"#FFC7CE\"      -- light red",
              ")"
            ],
            "lineageTag": "d9366aa2-0762-45c8-9567-b6e35371f42e"
          },
          {
            "name": "Sales YoY Arrow",
            "expression": [
              "",
              "VAR SalesCY =",
              "    [curr_year_sales]      -- your current year measure",
              "",
              "VAR SalesPY =",
              "    [prev_year_sales]      -- your previous year measure",
              "",
              "VAR Change =",
              "    DIVIDE( SalesCY - SalesPY, SalesPY )",
              "",
              "RETURN",
              "IF(",
              "    ISBLANK(Change),",
              "    BLANK(),",
              "    IF( Change > 0, \"\", \"\" )",
              ")"
            ],
            "lineageTag": "92f0dfe9-4a15-4d83-9956-231a6c315290"
          },
          {
            "name": "Sales YoY Change Numeric",
            "expression": [
              "",
              "VAR SalesCY = [curr_year_sales]      -- current year sales",
              "VAR SalesPY = [prev_year_sales]      -- previous year sales",
              "RETURN",
              "DIVIDE(SalesCY - SalesPY, SalesPY)"
            ],
            "lineageTag": "b2626db3-f8dd-471f-801d-8f8f3d975f28",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Sales YoY Change Text",
            "expression": [
              "",
              "VAR SalesCY = [curr_year_sales]      -- current year sales",
              "VAR SalesPY = [prev_year_sales]      -- previous year sales",
              "VAR Change = DIVIDE(SalesCY - SalesPY, SalesPY)",
              "VAR Sign = ",
              "    IF(Change >= 0, \"+\", \"-\")",
              "RETURN",
              "Sign & FORMAT( ABS(Change), \"0.000\" )"
            ],
            "lineageTag": "07959623-483a-43ce-9760-164d433ec16c"
          },
          {
            "name": "avg_order_value",
            "expression": "SUM('fact_sales'[NetSales])/[number_of_orders]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1e46fa58-ad7f-473b-b7a1-e5377fe3f8ee"
          },
          {
            "name": "quantity_sold",
            "expression": "COUNT('fact_sales'[QuantitySold])",
            "formatString": "#,0",
            "lineageTag": "417e19f0-981e-43a9-a24a-80af6eabfe42"
          },
          {
            "name": "ReturnedOrderAmountCY",
            "expression": [
              "",
              "CALCULATE (",
              "    [ReturnedOrderAmount],",
              "    DATESYTD ( dim_date[date] )",
              ")",
              ""
            ],
            "lineageTag": "c1d534b6-7ac9-484e-a4e2-a443e42a5611",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "returns_damaged",
            "expression": [
              "CALCULATE(",
              "    [number_of_returns],",
              "    'dim_return_reason'[ReturnReason] = \"Damaged\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "45334cbc-0fca-4351-b8b7-03e6fc3e5def"
          },
          {
            "name": "returns_changedmind",
            "expression": [
              "CALCULATE(",
              "    [number_of_returns],",
              "    'dim_return_reason'[ReturnReason] = \"Changed Mind\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fcb3af80-1ed7-49a8-bc81-a7fdcc59ba79"
          },
          {
            "name": "returns_size",
            "expression": [
              "CALCULATE(",
              "    [number_of_returns],",
              "    'dim_return_reason'[ReturnReason] = \"size issue\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "283f0642-0a5a-42aa-9066-c44660fc6f91"
          },
          {
            "name": "returns_notasdescribed",
            "expression": [
              "CALCULATE(",
              "    [number_of_returns],",
              "    'dim_return_reason'[ReturnReason] = \"not as described\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "aa4aff26-f390-493f-a932-d143595bbd2b"
          },
          {
            "name": "label_b2c",
            "expression": [
              "VAR BaseSalesB2C = ",
              "    CALCULATE(",
              "        SUM('fact_sales'[NetSales]),",
              "        'dim_channel'[ChannelName (3)] = \"B2C\"",
              "    )",
              "",
              "VAR TotalSales = SUM('fact_sales'[NetSales])",
              "",
              "-- STEP 1: Explicitly convert the sales amount to millions (e.g., 25,750,000 becomes 25.75)",
              "VAR SalesB2CInMillions = ",
              "    DIVIDE(BaseSalesB2C, 1000000)",
              "",
              "-- STEP 2: Format the millions value with a dollar sign, two decimals, and the 'M' suffix",
              "VAR SalesB2CFormatted = ",
              "    FORMAT(",
              "        SalesB2CInMillions,",
              "        \"$ 0.0 M\" -- The format \"0.00\" ensures two decimal places.",
              "    )",
              "",
              "-- STEP 3: Calculate the percentage (e.g., 0.2575)",
              "VAR PercentageB2C = ",
              "    DIVIDE(",
              "        BaseSalesB2C,",
              "        TotalSales",
              "    )",
              "",
              "-- STEP 4: Format the percentage value with two decimal places (e.g., 25.75 %)",
              "VAR PercentageB2CFormatted = ",
              "    FORMAT(",
              "        PercentageB2C,",
              "        \"0 %\" -- The format \"0.00 %\" ensures two decimal places for the percentage.",
              "    )",
              "",
              "RETURN ",
              "    -- Concatenate all parts into the final string",
              "    SalesB2CFormatted & \" (\" & PercentageB2CFormatted & \")\""
            ],
            "lineageTag": "8450d139-e76b-4010-ae0e-62f241fd4d5b"
          },
          {
            "name": "label_b2b",
            "expression": [
              "",
              "VAR BaseSalesB2B = ",
              "    CALCULATE(",
              "        SUM('fact_sales'[NetSales]),",
              "        -- Filter changed to B2B",
              "        'dim_channel'[ChannelName (3)] = \"B2B\" ",
              "    )",
              "",
              "VAR TotalSales = SUM('fact_sales'[NetSales])",
              "",
              "-- STEP 1: Explicitly convert the sales amount to millions ",
              "VAR SalesB2BInMillions = ",
              "    DIVIDE(BaseSalesB2B, 1000000)",
              "",
              "-- STEP 2: Format the millions value with a dollar sign, two decimals, and the 'M' suffix",
              "VAR SalesB2BFormatted = ",
              "    FORMAT(",
              "        SalesB2BInMillions,",
              "        \"$ 0.0 M\"",
              "    )",
              "",
              "-- STEP 3: Calculate the percentage ",
              "VAR PercentageB2B = ",
              "    DIVIDE(",
              "        BaseSalesB2B,",
              "        TotalSales",
              "    )",
              "",
              "-- STEP 4: Format the percentage value with two decimal places",
              "VAR PercentageB2BFormatted = ",
              "    FORMAT(",
              "        PercentageB2B,",
              "        \"0 %\"",
              "    )",
              "",
              "RETURN ",
              "    -- Concatenate all parts into the final string",
              "    SalesB2BFormatted & \" (\" & PercentageB2BFormatted & \")\""
            ],
            "lineageTag": "9a36f171-b070-4927-9247-91ede0a060cd"
          },
          {
            "name": "NetSales_YoY_Diff",
            "expression": [
              "",
              "VAR CurrSales = SUM ( 'fact_sales'[NetSales] )",
              "VAR PrevYearSales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[NetSales] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR SalesDiff = CurrSales - PrevYearSales",
              "VAR SalesDiffPct = DIVIDE ( SalesDiff, PrevYearSales )",
              "",
              "-- Only add + symbol if the difference is positive",
              "VAR PlusSymbol = IF ( SalesDiff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    -- Format the absolute difference (e.g., -$1,500 or +$5,000)",
              "    FORMAT ( SalesDiff, \"$#,##0\" )",
              "        & \"  |  \"",
              "        -- Format the percentage difference (e.g., +15% vs PY)",
              "        & PlusSymbol & FORMAT ( SalesDiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "41699488-78d5-4fb0-90d1-bae3640e195e"
          },
          {
            "name": "NetSales_YOY_Arrow",
            "expression": [
              "",
              "VAR CurrSales = SUM ( 'fact_sales'[NetSales] )",
              "VAR PrevMonthSales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[NetSales] ),",
              "        DATEADD ( 'dim_date'[Date], -1, Year )",
              "    )",
              "VAR SalesDiff = CurrSales - PrevMonthSales",
              "RETURN ",
              "    IF ( ",
              "        SalesDiff > 0, ",
              "        \"\",",
              "        IF ( ",
              "            SalesDiff < 0, ",
              "            \"\",",
              "            \"\"",
              "        )",
              "    )"
            ],
            "lineageTag": "efa3aa55-770f-4810-bb7a-050d8b99ce12"
          },
          {
            "name": "NetSales_YoY_Color",
            "expression": [
              "",
              "VAR CurrSales = SUM ( 'fact_sales'[NetSales] )",
              "VAR PrevYearSales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[NetSales] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR SalesDiff = CurrSales - PrevYearSales",
              "RETURN ",
              "    IF ( ",
              "        SalesDiff > 0, ",
              "        \"#00B050\", -- Green for positive change",
              "        IF ( ",
              "            SalesDiff < 0, ",
              "            \"#FF0000\", -- Red for negative change",
              "            \"#808080\" -- Grey for no change (optional, but good practice)",
              "        )",
              "    )"
            ],
            "lineageTag": "aca34d11-3b52-49b1-8880-469f5441ea83"
          },
          {
            "name": "QuantitySold_YoY_Arrow",
            "expression": [
              "",
              "VAR CurrQty = [quantity_sold]",
              "VAR PrevYearQty =",
              "    CALCULATE (",
              "        [quantity_sold],",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR QtyDiff = CurrQty - PrevYearQty",
              "RETURN ",
              "    IF ( ",
              "        QtyDiff > 0, ",
              "        \"\", -- Up arrow for increase",
              "        IF ( ",
              "            QtyDiff < 0, ",
              "            \"\", -- Down arrow for decrease",
              "            \"\" -- Solid square for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "c4a379da-cf4d-48c9-a8f8-e1e57fade6e5"
          },
          {
            "name": "QuantitySold_YoY_Color",
            "expression": [
              "",
              "VAR CurrQty = [quantity_sold]",
              "VAR PrevYearQty =",
              "    CALCULATE (",
              "        [quantity_sold],",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR QtyDiff = CurrQty - PrevYearQty",
              "RETURN ",
              "    IF ( ",
              "        QtyDiff > 0, ",
              "        \"#00B050\", -- Green for increase",
              "        IF ( ",
              "            QtyDiff < 0, ",
              "            \"#FF0000\", -- Red for decrease",
              "            \"#808080\" -- Grey for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "e98d855a-0752-405b-84e1-baa4c1e96c62"
          },
          {
            "name": "QuantitySold_YoY_Diff",
            "expression": [
              "",
              "VAR CurrQty = [quantity_sold]",
              "VAR PrevYearQty =",
              "    CALCULATE (",
              "        [quantity_sold],",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR QtyDiff = CurrQty - PrevYearQty",
              "VAR QtyDiffPct = DIVIDE ( QtyDiff, PrevYearQty )",
              "",
              "-- Only add + symbol if the difference is positive",
              "VAR PlusSymbol = IF ( QtyDiff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    -- Format the absolute difference (e.g., -150 or +500)",
              "    FORMAT ( QtyDiff, \"#,##0\" )",
              "        & \"  |  \"",
              "        -- Format the percentage difference (e.g., +15% vs PY)",
              "        & PlusSymbol & FORMAT ( QtyDiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "84fd7d93-9212-4b7e-9f32-38e41f4b7955"
          },
          {
            "name": "GrossSales_YoY_Diff",
            "expression": [
              "",
              "VAR CurrGrossSales = SUM ( 'fact_sales'[GrossSales] )",
              "VAR PrevYearGrossSales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[GrossSales] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR GrossSalesDiff = CurrGrossSales - PrevYearGrossSales",
              "VAR GrossSalesDiffPct = DIVIDE ( GrossSalesDiff, PrevYearGrossSales )",
              "",
              "-- Only add + symbol if the difference is positive",
              "VAR PlusSymbol = IF ( GrossSalesDiff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    -- Format the absolute dollar difference (e.g., +$10,500 or -$2,000)",
              "    FORMAT ( GrossSalesDiff, \"$#,##0\" )",
              "        & \"  |  \"",
              "        -- Format the percentage difference (e.g., +8% vs PY)",
              "        & PlusSymbol & FORMAT ( GrossSalesDiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "7113971e-5168-4ac1-91f2-767be21696e8"
          },
          {
            "name": "GrossSales_YoY_Arrow",
            "expression": [
              "",
              "VAR CurrGrossSales = SUM ( 'fact_sales'[GrossSales] )",
              "VAR PrevYearGrossSales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[GrossSales] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR GrossSalesDiff = CurrGrossSales - PrevYearGrossSales",
              "RETURN ",
              "    IF ( ",
              "        GrossSalesDiff > 0, ",
              "        \"\", -- Up arrow for increase",
              "        IF ( ",
              "            GrossSalesDiff < 0, ",
              "            \"\", -- Down arrow for decrease",
              "            \"\" -- Solid square for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "99fa2ce7-faa1-4d0f-b011-8f84b9ef4ef5"
          },
          {
            "name": "GrossSales_YoY_Color",
            "expression": [
              "",
              "VAR CurrGrossSales = SUM ( 'fact_sales'[GrossSales] )",
              "VAR PrevYearGrossSales =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[GrossSales] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR GrossSalesDiff = CurrGrossSales - PrevYearGrossSales",
              "RETURN ",
              "    IF ( ",
              "        GrossSalesDiff > 0, ",
              "        \"#00B050\", -- Green for increase",
              "        IF ( ",
              "            GrossSalesDiff < 0, ",
              "            \"#FF0000\", -- Red for decrease",
              "            \"#808080\" -- Grey for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "d3a5104d-3674-4454-8c9a-3bbb41d14f8d"
          },
          {
            "name": "GrossProfit_YoY_Diff",
            "expression": [
              "",
              "VAR CurrProfit = SUM ( 'fact_sales'[GrossProfit] )",
              "VAR PrevYearProfit =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[GrossProfit] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR ProfitDiff = CurrProfit - PrevYearProfit",
              "VAR ProfitDiffPct = DIVIDE ( ProfitDiff, PrevYearProfit )",
              "",
              "-- Only add + symbol if the difference is positive",
              "VAR PlusSymbol = IF ( ProfitDiff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    -- Format the absolute dollar difference (e.g., +$5,000 or -$1,000)",
              "    FORMAT ( ProfitDiff, \"$#,##0\" )",
              "        & \"  |  \"",
              "        -- Format the percentage difference (e.g., +12% vs PY)",
              "        & PlusSymbol & FORMAT ( ProfitDiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "91f5c8f1-2e60-4ae3-accd-dea637f8cb60"
          },
          {
            "name": "GrossProfit_YoY_Arrow",
            "expression": [
              "",
              "VAR CurrProfit = SUM ( 'fact_sales'[GrossProfit] )",
              "VAR PrevYearProfit =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[GrossProfit] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR ProfitDiff = CurrProfit - PrevYearProfit",
              "RETURN ",
              "    IF ( ",
              "        ProfitDiff > 0, ",
              "        \"\", -- Up arrow for increase (good)",
              "        IF ( ",
              "            ProfitDiff < 0, ",
              "            \"\", -- Down arrow for decrease (bad)",
              "            \"\" -- Solid square for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "835a7dfc-fe3a-487b-a8a9-76a95a902715"
          },
          {
            "name": "GrossProfit_YoY_Color",
            "expression": [
              "",
              "VAR CurrProfit = SUM ( 'fact_sales'[GrossProfit] )",
              "VAR PrevYearProfit =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[GrossProfit] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR ProfitDiff = CurrProfit - PrevYearProfit",
              "RETURN ",
              "    IF ( ",
              "        ProfitDiff > 0, ",
              "        \"#00B050\", -- Green for increase",
              "        IF ( ",
              "            ProfitDiff < 0, ",
              "            \"#FF0000\", -- Red for decrease",
              "            \"#808080\" -- Grey for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "e73c265a-3363-4612-8a34-dbd6b5d4d643"
          },
          {
            "name": "Measure 3",
            "lineageTag": "05203a34-5d59-43b4-a7a3-66ec1a6a5ad8",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ]
          },
          {
            "name": "COGS_YoY_Arrow",
            "expression": [
              "",
              "VAR CurrCOGS = SUM ( 'fact_sales'[COGS] )",
              "VAR PrevYearCOGS =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[COGS] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR COGSDiff = CurrCOGS - PrevYearCOGS",
              "RETURN ",
              "    IF ( ",
              "        COGSDiff > 0, ",
              "        \"\", -- Up arrow for increase in COGS",
              "        IF ( ",
              "            COGSDiff < 0, ",
              "            \"\", -- Down arrow for decrease in COGS",
              "            \"\" -- Solid square for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "f93d311c-749f-43a5-995d-d629bc98eeba"
          },
          {
            "name": "COGS_YoY_Color",
            "expression": [
              "VAR CurrCOGS = SUM ( 'fact_sales'[COGS] )",
              "VAR PrevYearCOGS =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[COGS] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "VAR COGSDiff = CurrCOGS - PrevYearCOGS",
              "RETURN ",
              "    IF ( ",
              "        COGSDiff > 0, ",
              "        \"#FF0000\", -- Red for increase in cost (Bad performance)",
              "        IF ( ",
              "            COGSDiff < 0, ",
              "            \"#00B050\", -- Green for decrease in cost (Good performance)",
              "            \"#808080\" -- Grey for no change",
              "        )",
              "    )"
            ],
            "lineageTag": "80c854a1-de25-44dc-841b-ec8dea4341fb"
          },
          {
            "name": "COGS_YoY_Diff",
            "expression": [
              "",
              "VAR CurrCOGS = SUM ( 'fact_sales'[COGS] )",
              "VAR PrevYearCOGS =",
              "    CALCULATE (",
              "        SUM ( 'fact_sales'[COGS] ),",
              "        SAMEPERIODLASTYEAR ( 'dim_date'[Date] )",
              "    )",
              "",
              "VAR COGSDiff = CurrCOGS - PrevYearCOGS",
              "VAR COGSDiffPct = DIVIDE ( COGSDiff, PrevYearCOGS )",
              "",
              "-- Only add + symbol if the difference is positive",
              "VAR PlusSymbol = IF ( COGSDiff > 0, \"+\", \"\" )",
              "",
              "RETURN",
              "    -- Format the absolute dollar difference (e.g., +$500 or -$1,000)",
              "    FORMAT ( COGSDiff, \"$#,##0\" )",
              "        & \"  |  \"",
              "        -- Format the percentage difference (e.g., +10% vs PY)",
              "        & PlusSymbol & FORMAT ( COGSDiffPct, \"0%\" )",
              "        & \" vs PY\""
            ],
            "lineageTag": "9521c394-7d56-4493-ae45-e805874f5f3a"
          },
          {
            "name": "COGS (1)",
            "expression": "SUM('fact_financial_insights'[COGS])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7a384047-d0dc-451c-b07e-42774384792b"
          },
          {
            "name": "Gross Sales (1)",
            "expression": "SUM('fact_financial_insights'[Gross Sales])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "98d8088d-3cd8-402d-88b4-e494e01124a7"
          },
          {
            "name": "Gross Profit (1)",
            "expression": "SUM('fact_financial_insights'[Gross Profit])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c3e144f3-fcb0-4129-a316-9c22fedc1838"
          },
          {
            "name": "net_sales",
            "expression": "SUM('fact_sales'[NetSales])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6ba04ff7-bf78-438d-9951-752903076b3f"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_visits",
        "lineageTag": "3c58a8d1-27c0-41f4-a200-a5e665995f31",
        "columns": [
          {
            "name": "VisitID",
            "dataType": "string",
            "sourceColumn": "VisitID",
            "lineageTag": "69b7ce0c-ebf7-4247-88c4-a43f67839ecf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VisitDate",
            "dataType": "dateTime",
            "sourceColumn": "VisitDate",
            "formatString": "Long Date",
            "lineageTag": "93bc1e7b-4b95-4c6b-8496-7a6a195ff5cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "bd5adb1a-a251-4cb3-95da-6fa3473e5be2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "7095187d-abcd-40d4-b707-b133b1c128cc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "6cf6fea3-3137-4112-a599-a01d69dd8330",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ConvertedFlag",
            "dataType": "int64",
            "sourceColumn": "ConvertedFlag",
            "formatString": "0",
            "lineageTag": "16ed1e81-135d-494a-bcdd-7250c5f7b11e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ConversionOrderID",
            "dataType": "string",
            "sourceColumn": "ConversionOrderID",
            "lineageTag": "c375af35-722c-48ab-80e2-a4dbf5b962d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_visits",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\DIM\\fact_visits.csv\"),[Delimiter=\",\", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"VisitID\", type text}, {\"VisitDate\", type date}, {\"CustomerID\", type text}, {\"ChannelID\", type text}, {\"RegionID\", type text}, {\"ConvertedFlag\", Int64.Type}, {\"ConversionOrderID\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "number_of_visits",
            "expression": "count('fact_visits'[VisitID])",
            "formatString": "0",
            "lineageTag": "651e3d4a-e841-4147-97ca-3f629c4a17c2"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "fact_returns",
        "lineageTag": "6b9642b8-3cd0-4fc5-891c-48dbd133a14f",
        "columns": [
          {
            "name": "ReturnID",
            "dataType": "string",
            "sourceColumn": "ReturnID",
            "lineageTag": "48e0277c-5238-48b2-99c5-c379c9a154a8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "OrderID",
            "dataType": "string",
            "sourceColumn": "OrderID",
            "lineageTag": "d0f5dfef-40b6-4a44-88fc-101eb3a9fa70",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ProductID",
            "dataType": "string",
            "sourceColumn": "ProductID",
            "lineageTag": "982ee446-4ec5-4a10-83ea-34991aceb31f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CustomerID",
            "dataType": "string",
            "sourceColumn": "CustomerID",
            "lineageTag": "0793bba3-6009-429a-b018-218e10c4f382",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RegionID",
            "dataType": "string",
            "sourceColumn": "RegionID",
            "lineageTag": "9b1eac63-f3d0-4e36-ba7e-83f876ed7265",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChannelID",
            "dataType": "string",
            "sourceColumn": "ChannelID",
            "lineageTag": "2eee1678-9933-47e5-82aa-a6e5232fa729",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ReturnReasonID",
            "dataType": "string",
            "sourceColumn": "ReturnReasonID",
            "lineageTag": "0add2d4f-cc29-4560-a8ba-d378fd2255de",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ReturnDate",
            "dataType": "dateTime",
            "sourceColumn": "ReturnDate",
            "formatString": "Long Date",
            "lineageTag": "8ec55b43-081c-41a5-9226-0858415ee9a4",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "InspectionDate",
            "dataType": "string",
            "sourceColumn": "InspectionDate",
            "lineageTag": "14fe8129-c82d-41c7-b087-d9addff5dc80",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RefundDate",
            "dataType": "string",
            "sourceColumn": "RefundDate",
            "lineageTag": "8d8e78be-a1d9-4f31-b8c3-e231f0f55946",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RejectedDate",
            "dataType": "string",
            "sourceColumn": "RejectedDate",
            "lineageTag": "3a1f67e6-5bdc-4134-b7ca-9ab99df3f081",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Processing Status",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "VAR _val = TRIM ( fact_returns[rejecteddate] )",
              "RETURN",
              "IF (",
              "    _val = \"\" || _val = BLANK (),",
              "    \"Refund Issued\",",
              "    \"Return Claim Rejected\"",
              ")"
            ],
            "lineageTag": "86c7aea9-8307-4f74-9233-7c2d3c69ebb2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_returns",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\returns_table_fixed.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ReturnID\", type text}, {\"OrderID\", type text}, {\"ProductID\", type text}, {\"CustomerID\", type text}, {\"RegionID\", type text}, {\"ChannelID\", type text}, {\"ReturnReasonID\", type text}, {\"ReturnDate\", type text}, {\"InspectionDate\", type text}, {\"RefundDate\", type text}, {\"RejectedDate\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "number_of_returns",
            "expression": "DISTINCTCOUNT('fact_returns'[ReturnID])",
            "formatString": "#,0",
            "lineageTag": "e3a26be9-6048-4a2f-a595-f102083ea7b8"
          },
          {
            "name": "percentage_diff_prv_year_returns",
            "expression": [
              "",
              "VAR curr_year =",
              "    YEAR ( MAX ( 'fact_returns'[ReturnDate] ) )",
              "",
              "VAR curr_year_orders =",
              "    CALCULATE (",
              "        [number_of_returns],",
              "        YEAR ( 'fact_returns'[ReturnDate] ) = curr_year",
              "    )",
              "",
              "VAR prev_year_orders =",
              "    CALCULATE (",
              "        [number_of_returns],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              "    )",
              "",
              "",
              "VAR pct_change =",
              "    DIVIDE ( curr_year_orders - prev_year_orders, prev_year_orders )",
              "",
              "VAR sign =",
              "    IF ( pct_change > 0, \"+\", \"\" )   -- negative already has \"-\" automatically",
              "",
              "RETURN",
              "sign & FORMAT( pct_change, \"0.00%\" )",
              ""
            ],
            "lineageTag": "f5e7f54b-44ab-4646-a506-328f7928421b"
          },
          {
            "name": "curr_year_returns",
            "expression": [
              "VAR curr_year = Year(MAX('fact_returns'[ReturnDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [number_of_returns],",
              "        YEAR('fact_returns'[ReturnDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [number_of_returns],",
              "        YEAR('fact_returns'[ReturnDate]) = curr_year-1",
              ")",
              "",
              "RETURN",
              "curr_year_ORDERS"
            ],
            "formatString": "0",
            "lineageTag": "f47aec25-3269-4709-a076-fb01d0fc7726"
          },
          {
            "name": "prev_year_returns",
            "expression": [
              "VAR curr_year = Year(MAX('fact_returns'[ReturnDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [number_of_returns],",
              "        YEAR('fact_returns'[ReturnDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [number_of_returns],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              ")",
              "",
              "RETURN",
              "prev_year_ORDERS"
            ],
            "formatString": "0",
            "lineageTag": "b75f7959-cd19-48da-887b-da110204ac8b"
          },
          {
            "name": "returns_growth_color_kpi_rule",
            "expression": [
              "IF(",
              "    [curr_year_returns]>[prev_year_returns],",
              "    \"Red\",",
              "    \"Green\"",
              "    )"
            ],
            "lineageTag": "d78851b5-dfe5-4c6c-8e31-c7fbde8c39ed"
          },
          {
            "name": "returns_growth_color_kpi_box_rule",
            "expression": [
              "",
              "IF(",
              "    [curr_year_returns] > [prev_year_returns],",
              "    \"#FFC7CE\",      -- light red",
              "    \"#C6EFCE\"     -- light green",
              ")"
            ],
            "lineageTag": "5668ddbc-347d-4552-b922-f09d07aa261c"
          },
          {
            "name": "Returns YoY Change Text",
            "expression": [
              "",
              "VAR ReturnsCY = [curr_year_returns]      -- current year sales",
              "VAR ReturnsPY = [prev_year_returns]      -- previous year sales",
              "VAR Change = DIVIDE(ReturnsCY - ReturnsPY, ReturnsPY)",
              "VAR Sign = ",
              "    IF(Change >= 0, \"+\", \"-\")",
              "RETURN",
              "Sign & FORMAT( ABS(Change), \"0.000\" )"
            ],
            "lineageTag": "6a7b5cf2-dbdb-4524-8179-50bbca047fb9"
          },
          {
            "name": "Total Returns",
            "expression": "COUNT('fact_returns'[ReturnID])",
            "formatString": "0",
            "lineageTag": "c6cb02d2-b980-4f51-be68-d364c2e78854"
          },
          {
            "name": "return_rate",
            "expression": "[number_of_returns] / [number_of_orders]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "966a7371-4aa2-442a-b511-f3afd1298c20"
          },
          {
            "name": "curr_year_return_rate",
            "expression": [
              "VAR curr_year = Year(MAX('fact_returns'[ReturnDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [return_rate],",
              "        YEAR('fact_returns'[ReturnDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [return_rate],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              ")",
              "",
              "RETURN",
              "curr_year_ORDERS"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7fde3e43-fa55-4740-a5a1-698844f56a82"
          },
          {
            "name": "prev_year_return_rate",
            "expression": [
              "VAR curr_year = Year(MAX('fact_returns'[ReturnDate]))",
              "var curr_year_ORDERS = CALCULATE(",
              "    [return_rate],",
              "        YEAR('fact_returns'[ReturnDate]) = curr_year",
              ")",
              "",
              "var prev_year_ORDERS = CALCULATE(",
              "    [return_rate],",
              "        DATEADD('dim_date'[Date],-1,YEAR)",
              ")",
              "",
              "RETURN",
              "prev_year_ORDERS"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "41cc8a75-feb8-44d3-a530-e304d1139091"
          },
          {
            "name": "Returns Rate YoY Change Text",
            "expression": [
              "",
              "VAR ReturnsCY = [curr_year_return_rate]      -- current year sales",
              "VAR ReturnsPY = [prev_year_return_rate]      -- previous year sales",
              "VAR Change = DIVIDE(ReturnsCY - ReturnsPY, ReturnsPY)",
              "VAR Sign = ",
              "    IF(Change >= 0, \"+\", \"-\")",
              "RETURN",
              "Sign & FORMAT( ABS(Change), \"0.000\" )"
            ],
            "lineageTag": "2fb58e20-9555-4db0-9c7e-6f592cc924c3"
          },
          {
            "name": "ReturnedOrderAmount",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( fact_orders[orderamount] ),",
              "    TREATAS ( VALUES ( fact_returns[orderid] ), fact_orders[orderid] )",
              ")",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "4ddce276-d192-4ea9-9e86-3a4d60566325"
          },
          {
            "name": "ReturnedOrderAmountPY",
            "expression": [
              "",
              "CALCULATE (",
              "    [ReturnedOrderAmount],",
              "    DATEADD ( dim_date[date], -1, YEAR )",
              ")"
            ],
            "lineageTag": "0bc2a43d-0e98-4261-b5e5-379008662708",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ReturnsYoYChangeText",
            "expression": [
              "",
              "VAR ReturnsCY = [ReturnedOrderAmountCY]",
              "VAR ReturnsPY = [ReturnedOrderAmountPY]",
              "VAR Change = DIVIDE(ReturnsCY - ReturnsPY, ReturnsPY)",
              "VAR Sign =",
              "    IF ( Change >= 0, \"+\", \"-\" )",
              "RETURN",
              "    Sign & FORMAT ( ABS ( Change ), \"0.000\" )",
              "",
              ""
            ],
            "lineageTag": "962488e7-5f14-4eac-a197-dc4919ba8ac6"
          },
          {
            "name": "Returns_Detail_Measure",
            "expression": [
              "",
              "---------------------------------------------",
              "-- Current period",
              "---------------------------------------------",
              "VAR Curr =",
              "    [number_of_returns]",
              "",
              "---------------------------------------------",
              "-- Previous year (YoY)",
              "---------------------------------------------",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [number_of_returns],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "---------------------------------------------",
              "-- Differences",
              "---------------------------------------------",
              "VAR Diff = Curr - PrevYear",
              "VAR DiffPct = DIVIDE(Diff, PrevYear)",
              "",
              "VAR PlusSign = IF(DiffPct > 0, \"+\", \"\")",
              "",
              "RETURN",
              "FORMAT(Diff, \"#,0\")",
              "    & \" | \"",
              "    & PlusSign",
              "    & FORMAT(DiffPct, \"0.0%\")",
              "    & \" vs PY\""
            ],
            "lineageTag": "6b3c2f8e-2f95-4258-80fb-00ed98f38492"
          },
          {
            "name": "Returns_Arrow_Measure",
            "expression": [
              "",
              "VAR Curr =",
              "    [number_of_returns]",
              "",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [number_of_returns],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "RETURN",
              "IF(Curr < PrevYear, \"\", \"\")"
            ],
            "lineageTag": "2871620b-6dcd-4265-9df5-26e3450e6a3f"
          },
          {
            "name": "Return_Rate_Detail_Measure",
            "expression": [
              "",
              "VAR Curr =",
              "    [return_rate]",
              "",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [return_rate],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR Diff =",
              "    Curr - PrevYear",
              "",
              "RETURN",
              "FORMAT(Diff, \"0.00%\")",
              "    & \" vs PY\""
            ],
            "lineageTag": "1e255db7-d98a-40d0-9153-25f5661f4347"
          },
          {
            "name": "Return_Rate_Arrow_Measure",
            "expression": [
              "",
              "VAR Curr =",
              "    [return_rate]",
              "",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [return_rate],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "RETURN",
              "IF(Curr < PrevYear, \"\", \"\")"
            ],
            "lineageTag": "a8a62d03-bf1d-4ed0-ad2d-4c5c5ee88c51"
          },
          {
            "name": "Return_Rate_Color_Measure",
            "expression": [
              "",
              "VAR Curr =",
              "    [return_rate]",
              "",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [return_rate],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "RETURN",
              "IF(Curr < PrevYear, \"#00B050\", \"#FF0000\")"
            ],
            "lineageTag": "24433fad-d3fd-48ef-ba9a-b3d2b55e3f27"
          },
          {
            "name": "returns_growth_color_kpi_rule_2",
            "expression": [
              "IF(",
              "    [curr_year_returns]>[prev_year_returns],",
              "   \"#FF0000\",\"#00B050\" ",
              "    )"
            ],
            "lineageTag": "570c6b4a-b155-4334-bab2-cf2dbb4425d2"
          },
          {
            "name": "ReturnedOrderAmount_Detail",
            "expression": [
              "VAR Curr =",
              "    [ReturnedOrderAmount]",
              "",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [ReturnedOrderAmount],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "VAR Diff = Curr - PrevYear",
              "VAR DiffPct = DIVIDE(Diff, PrevYear)",
              "",
              "-- Display amount in K",
              "VAR DiffK = DIVIDE(ABS(Diff), 1000)",
              "",
              "VAR PlusSign = IF(DiffPct > 0, \"+\", \"\")",
              "",
              "-- Determine sign for currency",
              "VAR SignAmt = IF(Diff < 0, \"- \", \"\")",
              "",
              "RETURN",
              "SignAmt & \"$\" & FORMAT(DiffK, \"#,0\") & \"K | \"",
              "    & PlusSign & FORMAT(DiffPct, \"0.0%\") & \" vs PY\""
            ],
            "lineageTag": "82298bfd-6f2e-4419-b935-9b1724793529"
          },
          {
            "name": "ReturnedOrderAmount_Arrow",
            "expression": [
              "",
              "VAR Curr =",
              "    [ReturnedOrderAmount]",
              "",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [ReturnedOrderAmount],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "RETURN",
              "IF(Curr < PrevYear, \"\", \"\")"
            ],
            "lineageTag": "e4855131-933b-4963-bdb3-7741414dac61"
          },
          {
            "name": "ReturnedOrderAmount_Color",
            "expression": [
              "",
              "VAR Curr =",
              "    [ReturnedOrderAmount]",
              "",
              "VAR PrevYear =",
              "    CALCULATE(",
              "        [ReturnedOrderAmount],",
              "        SAMEPERIODLASTYEAR('dim_date'[Date])",
              "    )",
              "",
              "RETURN",
              "IF(Curr < PrevYear, \"#00B050\", \"#FF0000\")"
            ],
            "lineageTag": "ebe4f1b3-82ee-4eb7-be7b-f3e0459e8f33"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "dim_date",
        "lineageTag": "6a61a872-916b-4338-abd9-fb7c617afffc",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "5018bf8d-fe19-4bf4-b9e3-a62718963159",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Year]",
            "formatString": "0",
            "lineageTag": "c6cea8f3-1a21-4b1b-b862-3c0c5e190555",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Year Month]",
            "lineageTag": "7ad76f45-fcd4-425d-b262-ce7b415f863b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Month Number]",
            "formatString": "0",
            "lineageTag": "1864d82e-6651-47b2-9b88-534eacfd76b6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Month Name]",
            "sortByColumn": "Month Number",
            "lineageTag": "d8501b1d-4433-4c3e-9caa-d73309d198d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Short Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Short Month]",
            "sortByColumn": "Month Number",
            "lineageTag": "5ccc4093-834d-4a55-bad5-d8c665cb91ae",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Quarter]",
            "lineageTag": "7e6124e5-4c2c-43ca-a00b-90af5920d737",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Year Quarter]",
            "lineageTag": "328ae3d2-f112-4a0d-bb5d-04066cb607fe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Week Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Week Number]",
            "formatString": "0",
            "lineageTag": "b833dd10-16ae-402f-abd8-cfd30c9fc3e2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Day]",
            "formatString": "0",
            "lineageTag": "71ca6ca2-01d5-4ee8-88fd-5e69ecd2712d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Day Name]",
            "lineageTag": "b0af8a3a-8b74-4ce9-b158-ad302de720c2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Short Day",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Short Day]",
            "lineageTag": "aa5c0864-e2e6-43bf-bd3c-ad847d6707ad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Is Weekend",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Is Weekend]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "77e4b205-cbbc-499d-90e4-44d2d8381a03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Start of Month",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Start of Month]",
            "formatString": "General Date",
            "lineageTag": "102fda65-76be-4c36-9904-8bbd0bac874e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "End of Month",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[End of Month]",
            "formatString": "General Date",
            "lineageTag": "71293e18-39fe-4a69-a7c1-9c2842eb471e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Start of Quarter",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Start of Quarter]",
            "formatString": "General Date",
            "lineageTag": "27f9db45-1e0f-4de1-a170-e67f56efabe6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "End of Quarter",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[End of Quarter]",
            "formatString": "General Date",
            "lineageTag": "6d45d94d-1c27-452d-bd05-08c160da94b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Start of Year",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Start of Year]",
            "formatString": "General Date",
            "lineageTag": "fc2f41d8-2882-4b4b-a7b3-38f5a91e15e2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "End of Year",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[End of Year]",
            "formatString": "General Date",
            "lineageTag": "ce75c46c-da0a-488f-a181-c98ec62a41ea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dim_date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR MinDate =",
                "    CALCULATE ( MIN ( 'fact_sales'[SalesDate] ), ALL ( 'fact_sales' ) )",
                "",
                "VAR MaxDate =",
                "    CALCULATE ( MAX ( 'fact_sales'[SalesDate] ), ALL ( 'fact_sales' ) )",
                "",
                "RETURN",
                "ADDCOLUMNS (",
                "    CALENDAR ( MinDate, MaxDate ),",
                "    \"Year\", YEAR ( [Date] ),",
                "    \"Year Month\", FORMAT ( [Date], \"YYYY-MM\" ),",
                "    \"Month Number\", MONTH ( [Date] ),",
                "    \"Month Name\", FORMAT ( [Date], \"MMMM\" ),",
                "    \"Short Month\", FORMAT ( [Date], \"MMM\" ),",
                "    \"Quarter\", \"Q\" & FORMAT ( [Date], \"Q\" ),",
                "    \"Year Quarter\", FORMAT ( [Date], \"YYYY\" ) & \"-Q\" & FORMAT ( [Date], \"Q\" ),",
                "    \"Week Number\", WEEKNUM ( [Date], 2 ),",
                "    \"Day\", DAY ( [Date] ),",
                "    \"Day Name\", FORMAT ( [Date], \"DDDD\" ),",
                "    \"Short Day\", FORMAT ( [Date], \"DDD\" ),",
                "    \"Is Weekend\", IF ( WEEKDAY ( [Date], 2 ) > 5, TRUE(), FALSE() ),",
                "    \"Start of Month\", EOMONTH ( [Date], -1 ) + 1,",
                "    \"End of Month\", EOMONTH ( [Date], 0 ),",
                "    \"Start of Quarter\",",
                "        DATE ( YEAR ( [Date] ), ( ( QUARTER ( [Date] ) - 1 ) * 3 ) + 1, 1 ),",
                "    \"End of Quarter\",",
                "        EOMONTH ( DATE ( YEAR ( [Date] ), ( ( QUARTER ( [Date] ) - 1 ) * 3 ) + 3, 1 ), 0 ),",
                "    \"Start of Year\", DATE ( YEAR ( [Date] ), 1, 1 ),",
                "    \"End of Year\", DATE ( YEAR ( [Date] ), 12, 31 )",
                ")",
                ""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4ab66b9dbf2149879de431f817c09d00"
          }
        ]
      },
      {
        "name": "fact_return_amount",
        "lineageTag": "87f7715a-8951-4817-ab36-41b2723c4d05",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "c585f32f-0846-4853-8005-271fc5b21ed4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Sales Returns Amount",
            "dataType": "decimal",
            "sourceColumn": "Sales Returns Amount",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "17811b8d-79ea-4124-9b1e-60cbf25385c3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_return_amount",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\Sales\\DIM\\fact_return_amount.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Sales Returns Amount\", Currency.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "return_amount_min_max",
            "expression": [
              "VAR CurrentMonthTotal =",
              "    -- 1. Get the total return amount for the current month in the visual",
              "    SUM ( 'fact_return_amount'[sales returns amount] )",
              "VAR AllMonthsReturns =",
              "    -- 2. Create a table of all monthly totals (Month Name and Total Return)",
              "    --    This is the key to correctly finding the global max/min total.",
              "    CALCULATETABLE (",
              "        ADDCOLUMNS (",
              "            VALUES ( 'dim_date'[month name] ),",
              "            \"MonthlyTotal\", SUM ( 'fact_return_amount'[sales returns amount] )",
              "        ),",
              "        ALLSELECTED ( 'dim_date' ) -- Clear filter on 'dim_date' table",
              "    )",
              "VAR MaxReturnAmount =",
              "    -- 3. Find the maximum value from the \"MonthlyTotal\" column in the table above",
              "    MAXX ( AllMonthsReturns, [MonthlyTotal] )",
              "VAR MinReturnAmount =",
              "    -- 4. Find the minimum value from the \"MonthlyTotal\" column in the table above",
              "    MINX ( AllMonthsReturns, [MonthlyTotal] )",
              "RETURN",
              "    -- 5. Check if the current month's total matches the global max or min total",
              "    IF (",
              "        CurrentMonthTotal = MaxReturnAmount,",
              "        -- Color Red for Max:",
              "        \"#FF0000\",",
              "        IF (",
              "            CurrentMonthTotal = MinReturnAmount,",
              "            -- Color Green (00B050) for Min:",
              "            \"#00B050\",",
              "            -- Color Blue (118DFF) for others:",
              "            \"#118DFF\"",
              "        )",
              "    )"
            ],
            "lineageTag": "8ba526f6-3f46-4728-a10e-09f3c59f2a9d"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Parameter",
        "lineageTag": "6e25710f-6bbf-4467-b5a4-f49f5b4a255c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Parameter",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Parameter Order",
            "lineageTag": "b9662ac5-a2c8-4723-a620-dbc4e103421a",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parameter Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Parameter Order",
            "lineageTag": "ae899f1b-fe62-45b6-9f40-e6817f32a4e3",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parameter Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "39392e4f-d61d-4f42-8314-454453d9c1e1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Gross Sales\", NAMEOF([Gross Sales (1)]), 0),",
                "    (\"COGS \", NAMEOF([COGS (1)]), 1),",
                "    (\"Gross Profit\", NAMEOF([Gross Profit (1)]), 2)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "142715d5f7244267a496b396db6ebc71"
          }
        ]
      },
      {
        "name": "Parameter (Overview)",
        "lineageTag": "396d8a5d-b49b-48ef-a64a-3d9dd2dcb7c7",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Parameter (Overview)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Parameter (Overview) Order",
            "lineageTag": "ef475dc8-15f1-460a-9c5e-779ab544e8a4",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter (Overview) Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parameter (Overview) Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Parameter (Overview) Order",
            "lineageTag": "45c337f4-33b0-4112-aa79-108400510978",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Parameter (Overview) Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "fb58ad49-56db-4cbd-8ac6-1e6563f3b64e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Parameter (Overview)",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Sales\", NAMEOF('fact_sales'[net_sales]), 0),",
                "    (\"Customers\", NAMEOF('fact_orders'[number_of_customers]), 1),",
                "    (\"Orders\", NAMEOF('fact_orders'[number_of_orders]), 2),",
                "    (\"Returns\", NAMEOF('fact_returns'[number_of_returns]), 3)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3646e45c86e74d32970a7e3540d6c68a"
          }
        ]
      },
      {
        "name": "fact_financial_insights",
        "lineageTag": "1e565772-7bd4-4b5b-88d1-c7934a1f270d",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "2439c1fa-1cb6-4735-b919-362152b33ae3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Gross Sales",
            "dataType": "decimal",
            "sourceColumn": "Gross Sales",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "01b794ed-ff10-480a-801d-9b85f95a22c0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "COGS",
            "dataType": "decimal",
            "sourceColumn": "COGS",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "31036082-ebc9-4235-b536-eedac154ab53",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Gross Profit",
            "dataType": "decimal",
            "sourceColumn": "Gross Profit",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "56b4c17c-fd3e-4fdc-b71c-1f82d3b3d3f4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "fact_financial_insights",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\CAM Tech\\Downloads\\BI Project\\Sales\\DIM\\fact_financial_insights.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Gross Sales\", Currency.Type}, {\"COGS\", Currency.Type}, {\"Gross Profit\", Currency.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "KPI_Summary_Table",
        "lineageTag": "1c6ec32a-7b85-446c-af04-71873eff9fb3",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "KPI Category",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[KPI Category]",
            "lineageTag": "40842d83-dfe6-47b1-a9eb-486cdacd8e70",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "KPI Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[KPI Name]",
            "lineageTag": "fd324d9f-7602-4cc4-b18c-3cacf4b4d2d4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "KPI Value",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[KPI Value]",
            "lineageTag": "5386a76f-4aad-4d42-9962-b5c345f4fa89",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Metric Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Metric Name]",
            "lineageTag": "2e24d854-1dde-4fc8-9d4c-e386e0160c4a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Metric Value",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Metric Value]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0508367d-4aa6-4795-ac3d-611aec700f4b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "KPI_Summary_Table",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "// Variables for calculations (not used for % of total, but good practice to keep)",
                "VAR TotalSales = CALCULATE(SUM(fact_sales[netsales]), ALL('fact_sales'))",
                "VAR TotalProfit = CALCULATE(SUM(fact_sales[grossprofit]), ALL('fact_sales'))",
                "",
                "// 1. Most Sales Generating Country (dim_region[country])",
                "VAR CountrySales =",
                "    TOPN(",
                "        1,",
                "        SUMMARIZE(",
                "            ALL('dim_region'[country]),",
                "            'dim_region'[country],",
                "            \"Sales\", SUM(fact_sales[netsales])",
                "        ),",
                "        [Sales], DESC",
                "    )",
                "VAR FormattedCountry =",
                "    SELECTCOLUMNS(",
                "        CountrySales,",
                "        \"KPI Category\", \"Most Sales Generating Country\",",
                "        \"KPI Name\", \"Country Name\",",
                "        \"KPI Value\", 'dim_region'[country],",
                "        \"Metric Name\", \"Total Sales\",",
                "        \"Metric Value\", [Sales]",
                "    )",
                "",
                "// 2. Most Profitable Region (dim_region[continent])",
                "VAR RegionProfit =",
                "    TOPN(",
                "        1,",
                "        SUMMARIZE(",
                "            ALL('dim_region'[continent]),",
                "            'dim_region'[continent],",
                "            \"Gross Profit\", SUM(fact_sales[grossprofit])",
                "        ),",
                "        [Gross Profit], DESC",
                "    )",
                "VAR FormattedRegion =",
                "    SELECTCOLUMNS(",
                "        RegionProfit,",
                "        \"KPI Category\", \"Most Profitable Region\",",
                "        \"KPI Name\", \"Region Name\",",
                "        \"KPI Value\", 'dim_region'[continent],",
                "        \"Metric Name\", \"Total Gross Profit\",",
                "        \"Metric Value\", [Gross Profit]",
                "    )",
                "",
                "// 3. Top Selling Product (dim_product[productname])",
                "VAR ProductSales =",
                "    TOPN(",
                "        1,",
                "        SUMMARIZE(",
                "            ALL('dim_product'[productname]),",
                "            'dim_product'[productname],",
                "            \"Sales\", SUM(fact_sales[netsales])",
                "        ),",
                "        [Sales], DESC",
                "    )",
                "VAR FormattedProduct =",
                "    SELECTCOLUMNS(",
                "        ProductSales,",
                "        \"KPI Category\", \"Top Selling Product\",",
                "        \"KPI Name\", \"Product Name\",",
                "        \"KPI Value\", 'dim_product'[productname],",
                "        \"Metric Name\", \"Total Sales\",",
                "        \"Metric Value\", [Sales]",
                "    )",
                "",
                "// 4. Top Buying Customer (NEW - dim_customer[fullname])",
                "VAR CustomerSales =",
                "    TOPN(",
                "        1,",
                "        SUMMARIZE(",
                "            ALL('dim_customer'[fullname]),",
                "            'dim_customer'[fullname],",
                "            \"Sales\", SUM(fact_sales[netsales])",
                "        ),",
                "        [Sales], DESC",
                "    )",
                "VAR FormattedCustomer =",
                "    SELECTCOLUMNS(",
                "        CustomerSales,",
                "        \"KPI Category\", \"Top Buying Customer\",",
                "        \"KPI Name\", \"Customer Name\",",
                "        \"KPI Value\", 'dim_customer'[fullname],",
                "        \"Metric Name\", \"Total Sales\",",
                "        \"Metric Value\", [Sales]",
                "    )",
                "",
                "RETURN",
                "    UNION(",
                "        FormattedCountry,",
                "        FormattedRegion,",
                "        FormattedProduct,",
                "        FormattedCustomer // Added the new customer table",
                "    )"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9b1fbef8dfbc4fea9f2c8b7cb76b749c"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "11ec6937-c75f-852f-2ae6-6ec03616dcc1",
        "fromTable": "fact_visits",
        "fromColumn": "ChannelID",
        "toTable": "dim_channel",
        "toColumn": "ChannelID"
      },
      {
        "name": "8ed8b1d9-2a3f-6b14-69e6-6a73ed38f0e7",
        "fromTable": "fact_visits",
        "fromColumn": "CustomerID",
        "toTable": "dim_customer",
        "toColumn": "CustomerID"
      },
      {
        "name": "14143c22-3e29-e48b-2165-855f033e8e2f",
        "fromTable": "fact_sales",
        "fromColumn": "ChannelID",
        "toTable": "dim_channel",
        "toColumn": "ChannelID"
      },
      {
        "name": "e1653248-11e6-d6d7-4e1f-595e5965382c",
        "fromTable": "fact_sales",
        "fromColumn": "ProductID",
        "toTable": "dim_product",
        "toColumn": "ProductID"
      },
      {
        "name": "9d9860b9-1b81-f583-6791-8ab68c9cf69e",
        "fromTable": "fact_sales",
        "fromColumn": "RegionID",
        "toTable": "dim_region",
        "toColumn": "RegionID"
      },
      {
        "name": "a44be92b-2b5c-7bb5-5e20-5bca4c842aa1",
        "fromTable": "fact_orders",
        "fromColumn": "ChannelID",
        "toTable": "dim_channel",
        "toColumn": "ChannelID"
      },
      {
        "name": "c04ab984-a132-0bf6-3a75-0cfba2f9d4cb",
        "fromTable": "fact_orders",
        "fromColumn": "CustomerID",
        "toTable": "dim_customer",
        "toColumn": "CustomerID"
      },
      {
        "name": "164f8991-e748-807d-54fb-52a200919c24",
        "fromTable": "fact_orders",
        "fromColumn": "RegionID",
        "toTable": "dim_region",
        "toColumn": "RegionID"
      },
      {
        "name": "3c8a4799-816c-a84e-ff9d-1cdbba5f83af",
        "fromTable": "fact_visits",
        "fromColumn": "RegionID",
        "toTable": "dim_region",
        "toColumn": "RegionID"
      },
      {
        "name": "AutoDetected_4af7675b-c2b9-4366-a6f0-927bb5498779",
        "fromTable": "fact_returns",
        "fromColumn": "ChannelID",
        "toTable": "dim_channel",
        "toColumn": "ChannelID"
      },
      {
        "name": "AutoDetected_9709f58e-144a-4c58-a623-d425da0a7ec5",
        "fromTable": "fact_returns",
        "fromColumn": "CustomerID",
        "toTable": "dim_customer",
        "toColumn": "CustomerID"
      },
      {
        "name": "AutoDetected_14ea9d44-2152-4794-98de-f6d2fa44a54a",
        "fromTable": "fact_returns",
        "fromColumn": "ProductID",
        "toTable": "dim_product",
        "toColumn": "ProductID"
      },
      {
        "name": "AutoDetected_95af446f-6c0d-4648-8d15-628c4e04672e",
        "fromTable": "fact_returns",
        "fromColumn": "RegionID",
        "toTable": "dim_region",
        "toColumn": "RegionID"
      },
      {
        "name": "AutoDetected_3dd78157-c764-4c79-9825-2dc061cd2d72",
        "fromTable": "fact_returns",
        "fromColumn": "ReturnReasonID",
        "toTable": "dim_return_reason",
        "toColumn": "ReturnReasonID"
      },
      {
        "name": "fe6ea51a-1ed5-d55a-667c-a054284b4a24",
        "fromTable": "fact_returns",
        "fromColumn": "ReturnDate",
        "toTable": "dim_date",
        "toColumn": "Date"
      },
      {
        "name": "2d3d68c2-051e-00dc-d235-98df1dd77f28",
        "fromTable": "fact_orders",
        "fromColumn": "OrderDate",
        "toTable": "dim_date",
        "toColumn": "Date"
      },
      {
        "name": "f0278624-a79a-fef3-a843-4e1b7334bea6",
        "fromTable": "fact_sales",
        "fromColumn": "SalesDate",
        "toTable": "dim_date",
        "toColumn": "Date"
      },
      {
        "name": "670f150b-d8e5-4f71-2268-6cae0107732f",
        "fromTable": "fact_visits",
        "fromColumn": "VisitDate",
        "toTable": "dim_date",
        "toColumn": "Date"
      },
      {
        "name": "aade68bb-1747-3ae9-7749-e12adc34b356",
        "fromCardinality": "one",
        "fromTable": "fact_return_amount",
        "fromColumn": "Date",
        "toTable": "dim_date",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "3e574fd4-b0a6-9cd6-fafd-b11bc9a90c60",
        "fromCardinality": "one",
        "fromTable": "fact_financial_insights",
        "fromColumn": "Date",
        "toTable": "dim_date",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_channel\",\"dim_customer\",\"dim_product\",\"dim_region\",\"dim_return_reason\",\"fact_orders\",\"fact_sales\",\"fact_visits\",\"fact_returns\",\"fact_return_amount\",\"fact_financial_insights\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}